//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Gulan, Somato... whats next?"]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from hilltop. Assault and capture <marker name = 'target1'>Somato</marker>, <marker name = 'target3'>Gulan</marker> and <marker name = 'target2'>Factory</marker> objectives.<br/><br/>PMC Hillside<br/><br/>1. SITUATION:<br/>There is some serious enemy movement in the north, we are keeping an eye on it. In the mean time friendly troops morale is quite high.<br/><br/>2. MISSION:<br/>Assault and capture Gulan and downtown Somato.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from hilltop. Assault and capture <marker name = 'target1'>Somato</marker>, <marker name = 'target3'>Gulan</marker> and <marker name = 'target2'>Factory</marker> objectives. Bravo squad is moving in from Chantico, they will hold in <marker name = 'bfup'>B FUP</marker> point for your radio (0-0-1) call for them to attack. You can call in A10 close air support with radio (0-0-2) call.<br/><br/>4. SERVICE AND SUPPORT<br/>Additional infantry squad callsign 1-1-B, AH-1 Cobra gunship is standing by in case you need CAS. Use radio (0-0-2) to call A10 close air support.<br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture Gulan"];
objective3 setSimpleTaskDescription ["Capture Gulan", "Capture Gulan", "Capture Gulan"];
objective2 = player createSimpleTask ["Capture Factory"];
objective2 setSimpleTaskDescription ["Capture Factory", "Capture Factory", "Capture Factory"];
objective1 = player createSimpleTask ["Capture Somato"];
objective1 setSimpleTaskDescription ["Capture Somato", "Capture Somato", "Capture Somato"];
