//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Smell that cool ocean breeze, ahh, I love beaches... to fight on!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>harbor</marker> and <marker name = 'target2'>base</marker> objectives.



<br/><br/>PMC Cutoff<br/><br/>

1. SITUATION:<br/>
Our Special Operations Forces are conducting alot of missions behind enemy lines to disrupt their supply lines, communications and command. We will soon see how this pays off.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>harbor</marker> and <marker name = 'target2'>base</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Base"];
objective2 setSimpleTaskDescription ["Capture Base", "Capture Base", "Capture Base"];
objective1 = player createSimpleTask ["Capture Harbor"];
objective1 setSimpleTaskDescription ["Capture Harbor", "Capture Harbor", "Capture Harbor"];
