//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Foothold in Nogova, hooyah baby! Its awesome feeling to step into virgin terrain, I just love freeing up these islands from the dirty Russian hands.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airbase. Defend the airbase against Russian <marker name = 'target1'>counterattack</marker> from east.



<br/><br/>PMC D-fence<br/><br/>

1. SITUATION:<br/>
Russians were expecting us, there is now imminent counterattack launched towards the airbase, they do not want to let go of this island easily. Our forces are on the move into the airbase but it must be held until additional troops arrive.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from airbase. Defend the airbase against Russian <marker name = 'target1'>counterattack</marker> from east.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend airbase"];
objective1 setSimpleTaskDescription ["Defend airbase", "Defend airbase", "Defend airbase"];
