//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That last fight was intense, really intense. Everyone is like shook up after that fight.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Pesadas</marker>, <marker name = 'target2'>Pacamac</marker>, <marker name = 'target3'>comms tower</marker> and <marker name = 'target4'>houses</marker> objectives.



"]];
// tasks need to be in reversed order
objective4 = player createSimpleTask ["Capture houses"];
objective4 setSimpleTaskDescription ["Capture houses", "Capture houses", "Capture houses"];
objective3 = player createSimpleTask ["Capture comms tower"];
objective3 setSimpleTaskDescription ["Capture comms tower", "Capture comms tower", "Capture comms tower"];
objective2 = player createSimpleTask ["Capture Pacamac"];
objective2 setSimpleTaskDescription ["Capture Pacamac", "Capture Pacamac", "Capture Pacamac"];
objective1 = player createSimpleTask ["Capture Pesadas"];
objective1 setSimpleTaskDescription ["Capture Pesadas", "Capture Pesadas", "Capture Pesadas"];
