//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Here they come again, oh man, how long this is going to last this time.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Le Moule. Stop Russian <marker name = 'target1'>attack</marker> from east.



<br/><br/>PMC TheWall<br/><br/>

1. SITUATION:<br/>
Enemy is fighting in high intensity on the central Everon area, we must maintain our positions and not give into any of the enemys attacks. It is very important that we can proceed our offensive operations as quickly as possible.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Le Moule. Stop Russian <marker name = 'target1'>attack</marker> from east.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Stop Russians"];
objective1 setSimpleTaskDescription ["Stop Russians", "Stop Russians", "Stop Russians"];
