//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Beyond the bridges... I dont like this at all, we're cut off from our armor here.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Davle. Capture <marker name = 'target1'>Velka ves</marker> and <marker name = 'target2'>Lany</marker> objectives.



<br/><br/>PMC Lazy<br/><br/>

1. SITUATION:<br/>
Our forces have penetrated to the east side of the river and now we must focus all our air efforts to clear the way from any enemy armor. In the mean time there is some heavy enemy activity at north which we are closely monitoring also.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Davle. Capture <marker name = 'target1'>Velka ves</marker> and <marker name = 'target2'>Lany</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Lany"];
objective2 setSimpleTaskDescription ["Capture Lany", "Capture Lany", "Capture Lany"];
objective1 = player createSimpleTask ["Capture Velka ves"];
objective1 setSimpleTaskDescription ["Capture Velka ves", "Capture Velka ves", "Capture Velka ves"];
