//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


That western coastline approach looks mean.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>base</marker> and <marker name = 'target2'>ruins</marker> objectives.



<br/><br/>PMC Wildwest<br/><br/>

1. SITUATION:<br/>
Our war against the russians are continuing, our push forward should be straight out simple today. Enemy doesn't appear to have any major counter attacks planned according to their troop movements.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>base</marker> and <marker name = 'target2'>ruins</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Your support today is AH-1 Cobra gunship callsign Bravo Black. Call him on radio channel 0-0-1 to assault first the base and then ruins. You can find <marker name = 'ussup1'>vehicles</marker> being unloaded from LST ships on the shore.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Ruins"];
objective2 setSimpleTaskDescription ["Capture Ruins", "Capture Ruins", "Capture Ruins"];
objective1 = player createSimpleTask ["Capture Base"];
objective1 setSimpleTaskDescription ["Capture Base", "Capture Base", "Capture Base"];
