//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Time to move north, wonder how it is like there...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Lany. Capture <marker name = 'target1'>Bitov</marker> and <marker name = 'target2'>Blata</marker> objectives.



<br/><br/>PMC Pains<br/><br/>

1. SITUATION:<br/>
As we focus our efforts on the east central Nogova, we will bring a bear some CAS elements to support our ground troops. Enemy has some heavy vehicles located in that area which are threat to our forces.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Lany. Capture <marker name = 'target1'>Bitov</marker> and <marker name = 'target2'>Blata</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Todays support is Bradley squad, AH-64 Apache gunship and A-10 tank killer.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Blata"];
objective2 setSimpleTaskDescription ["Capture Blata", "Capture Blata", "Capture Blata"];
objective1 = player createSimpleTask ["Capture Bitov"];
objective1 setSimpleTaskDescription ["Capture Bitov", "Capture Bitov", "Capture Bitov"];
