//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Sahrani is going to fall baby!
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Mataredo</marker> and <marker name = 'target2'>northern base</marker> objectives.



"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture northern base"];
objective2 setSimpleTaskDescription ["Capture northern base", "Capture northern base", "Capture northern base"];
objective1 = player createSimpleTask ["Capture Mataredo"];
objective1 setSimpleTaskDescription ["Capture Mataredo", "Capture Mataredo", "Capture Mataredo"];
