//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Its nice to be high up on the hills.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from road, assault and capture
the <marker name = 'target1'>base #1</marker> and second <marker name = 'target2'>base #2</marker> bit
more to the east.
<br/><br/>
Good luck.



<br/><br/>PMC Ranger Mountain<br/><br/>

GEN SITREP<br/>
Our next objective is to capture the central island bases right up in the mountains. They
will be place where enemy soldiers have been shooting SA-7 missiles to our helos, its utmost
importance that we capture them ASAP.
<br/><br/>

INTEL<br/>
There are enemy AA emplacements as one of our helos was shot down yesterday south of target 2
position. You should not expect heavy armor as the area is rather narrow for them. Infantry is
mostly on defensive positions.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from road west from the first base, assault and 
capture the <marker name = 'target1'>base #1</marker> and also the 
second <marker name = 'target2'>base #2</marker> bit more to the east along the road. Mission is 
accomplished when both bases are under US control.
<br/><br/>

TACTICAL<br/>
Okay now we get some payback from the downed helo, the AA which got him came from one of (or both) 
these bases which you are tasked to kill. Be alert for north and south as the mountain range is very
steep, no armor or vehicles are to be expected from there but infantry assault is possible. So watch
your six.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture base #2"];
objective2 setSimpleTaskDescription ["Capture base #2", "Capture base #2", "Capture base #2"];
objective1 = player createSimpleTask ["Capture base #1"];
objective1 setSimpleTaskDescription ["Capture base #1", "Capture base #1", "Capture base #1"];
