//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Ok, now they're really pissed...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Chapoi, defend it.
<br/><br/>



<br/><br/>PMC Kings<br/><br/>

1. SITUATION:<br/>
Enemy is on now full alert on the whole island and its pushing hard on against us. We must hold them at bay at all costs.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Chapoi, defend it against the heavy russian armor attack coming from west.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Chapoi"];
objective1 setSimpleTaskDescription ["Defend Chapoi", "Defend Chapoi", "Defend Chapoi"];
