//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


I'm so looking foward of finishing this Nogova operation.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Blata. Capture <marker name = 'target1'>intersection</marker> and <marker name = 'target2'>Modrava</marker> objectives.



<br/><br/>PMC Holytown<br/><br/>

1. SITUATION:<br/>
Air strikes continue with the help of Special Operations Forces to pinpoint targets in the central, north east region of Nogova. At the same time we launch attack on enemy held positions in the north west part of the island.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Blata. Helicopter will <marker name = 'pickup'>pickup</marker> your team and ferry to the <marker name = 'lz'>LZ</marker> near Mirov. Join up with Charlie and Delta squads, then proceed to capture fortified <marker name = 'target1'>intersection</marker> and city of <marker name = 'target2'>Modrava</marker> objectives. Use radio 0-0-1 to issue the attack command from the <marker name = 'fup'>FUP</marker> near church.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Infantry squad Charlie and Bradley squad is waiting for attack command, use radio 0-0-1 to issue it.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Modrava"];
objective2 setSimpleTaskDescription ["Capture Modrava", "Capture Modrava", "Capture Modrava"];
objective1 = player createSimpleTask ["Capture intersection"];
objective1 setSimpleTaskDescription ["Capture intersection", "Capture intersection", "Capture intersection"];
