//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Final days ahead for the enemy. How do they take it?
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from La Trinite.
capture <marker name = 'target1'>Dourdan</marker> objective.
capture <marker name = 'target2'>Houdan</marker> objective.



<br/><br/>PMC Blowout<br/><br/>

1. SITUATION:<br/>
Enemy is really getting their act together on the final phases of our operation in the Malden island.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from La Trinite.
capture <marker name = 'target1'>Dourdan</marker> objective.
capture <marker name = 'target2'>Houdan</marker> objective.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Houdan"];
objective2 setSimpleTaskDescription ["Capture Houdan", "Capture Houdan", "Capture Houdan"];
objective1 = player createSimpleTask ["Capture Dourdan"];
objective1 setSimpleTaskDescription ["Capture Dourdan", "Capture Dourdan", "Capture Dourdan"];
