//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Heh, damn SLA, I hate those guys. We lost some men this morning, thats pissing me off, when I'm pissed ... I want to waste somebody, find me a SLA forces, please find me some..."]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from Chantico. Capture <marker name = 'target1'>Playa De Palomas</marker> and <marker name = 'target2'>huts</marker> objectives.<br/><br/>PMC Resorts<br/><br/>1. SITUATION:<br/>SLA counter attacks have been repelled, our operations continue on this region. Today we push forward showing to the enemy that we have the strenght to continue. We move towards the airbase at steady pace.<br/><br/>2. MISSION:<br/>Capture Playa De Palomas and resort hut objectives.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from Chantico. Capture <marker name = 'target1'>Playa De Palomas</marker> and resort <marker name = 'target2'>huts</marker> objectives.<br/><br/>4. SERVICE AND SUPPORT<br/><br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture huts"];
objective2 setSimpleTaskDescription ["Capture huts", "Capture huts", "Capture huts"];
objective1 = player createSimpleTask ["Capture Playa De Palomas"];
objective1 setSimpleTaskDescription ["Capture Playa De Palomas", "Capture Playa De Palomas", "Capture Playa De Palomas"];
