//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Capitol has fallen, now comes the pissed off counterattack hehe. Oh my...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Petrovice. Defend it against <marker name = 'target1'>counterattack</marker> from east.



<br/><br/>PMC Capitol Punishment<br/><br/>

1. SITUATION:<br/>
Our forces are now in control of Petrovice, capitol of Nogova. We are monitoring a heavy enemy counterattack heading from east towards the city, it is essential that our forces maintain their grounds in this location. We will send all support we got into the are to repel the enemy attack.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Petrovice. Defend it against <marker name = 'target1'>counterattack</marker> from east.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Petrovice"];
objective1 setSimpleTaskDescription ["Defend Petrovice", "Defend Petrovice", "Defend Petrovice"];
