//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Tanks to blow up, this can be tricky.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from forest. Take out 
enemy <marker name = 'target1'>Ammo Dump</marker> in the ruins 
and <marker name = 'target2'>Ammo Depot</marker> in the west.



<br/><br/>PMC Ranger Ammos<br/><br/>

GEN SITREP<br/>
Our Special Operations Forces have succesfully taken out the enemy communications nodes
over night and now our forces are closing in the Nogova west coast for full scale invasion.
<br/><br/>

INTEL<br/>
Ammo Dump contains lot of ammo and several tanks including T72 and T80. The crews dont
appear to be inside the tanks. Ammo Depot near airbase contains more activity and guards
and contains Shilka AAA vehicles.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from forest. Proceed just SE of the forest and 
take out the enemy <marker name = 'target1'>Ammo Dump</marker> in the ruins, it should contain
several tanks with crew resting nearby. Be quick about it. From there proceed west 
into <marker name = 'target2'>Ammo Depot</marker> near the airbase, assault and neutralize all
Russians in there. Do not destroy the equipment because we want to use it for our own 
purposes. Good luck.
<br/><br/>

TACTICAL<br/>
n/a
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Neutralize Ammo Depot"];
objective2 setSimpleTaskDescription ["Neutralize Ammo Depot", "Neutralize Ammo Depot", "Neutralize Ammo Depot"];
objective1 = player createSimpleTask ["Destroy Ammo Dump"];
objective1 setSimpleTaskDescription ["Destroy Ammo Dump", "Destroy Ammo Dump", "Destroy Ammo Dump"];
