//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


That was one hair raising enemy counter attack. And now the best part is that HQ tells me there is another one coming, beautiful...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airbase. Defend it against <marker name = 'target1'>counter attack</marker> from south.



<br/><br/>PMC Stir 2<br/><br/>

1. SITUATION:<br/>
Enemy launched large scare counter attack to the airbase which our forces are holding. They seems to mobilize even more troops as we prepare for another attack, this might not be over so soon.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from airbase. Defend it against <marker name = 'target1'>counter attack</marker> from south.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Airbase"];
objective1 setSimpleTaskDescription ["Defend Airbase", "Defend Airbase", "Defend Airbase"];
