//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Today I'm going to blow some ruskies up...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Levie. Capture <marker name = 'target1'>Regina</marker> and <marker name = 'target2'>Durras</marker> objectives.



<br/><br/>PMC Saphire<br/><br/>

1. SITUATION:<br/>
It looks like enemy starts to panic as they make very hastily tactical moves on the battlefield. If we keep this momentum up, the war will be over in no time.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Levie. Capture <marker name = 'target1'>Regina</marker> and <marker name = 'target2'>Durras</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Durras"];
objective2 setSimpleTaskDescription ["Capture Durras", "Capture Durras", "Capture Durras"];
objective1 = player createSimpleTask ["Capture Regina"];
objective1 setSimpleTaskDescription ["Capture Regina", "Capture Regina", "Capture Regina"];
