//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Okay so another counterattack coming, ok this time I'll do some major damage with minimum losses to friendly forces.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Lamentin. Defend <marker name = 'lemoule'>Le Moule</marker> against enemy <marker name = 'target1'>counter attack</marker> from south east.



<br/><br/>PMC Badmoon<br/><br/>

1. SITUATION:<br/>
There is wave of enemy attacks coming in the north west part of Everon, we will keep the enemy at bay but closely monitor the situation so it wont get out of hand. Coordinating our troops according to the minute by minute war picture.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Lamentin. Take the truck and race into <marker name = 'lemoule'>Le Moule</marker> which is becoming under enemy attack. Dedend it against enemy <marker name = 'target1'>counter attack</marker> from south east.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Echo Black is M1A1 Abrams Platoon. Bravo and Charlie Black is Mechanized infantry platoons. Delta Black is AH-64 Apache.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Le Moule"];
objective1 setSimpleTaskDescription ["Defend Le Moule", "Defend Le Moule", "Defend Le Moule"];
