//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "rumour"]];
player createDiaryRecord ["Diary", ["Mission", "You <marker name = 'start'>start</marker> in HQ. Clear <marker name = 'target1'>target1</marker>, <marker name = 'target2'>target2</marker>, <marker name = 'target3'>target3</marker> and <marker name = 'target4'>target4</marker> objectives."]];

// tasks need to be in reversed order
objective4 = player createSimpleTask ["Target 4"];
objective4 setSimpleTaskDescription ["Target 4", "Target 4", "Target 4"];
objective3 = player createSimpleTask ["Target 3"];
objective3 setSimpleTaskDescription ["Target 3", "Target 3", "Target 3"];
objective2 = player createSimpleTask ["Target 2"];
objective2 setSimpleTaskDescription ["Target 2", "Target 2", "Target 2"];
objective1 = player createSimpleTask ["Target 1"];
objective1 setSimpleTaskDescription ["Target 1", "Target 1", "Target 1"];
