//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



I have some bullets awaiting for for the enemy, I'm expecting them to meet soon.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Estrella</marker>, <marker name = 'target2'>Cedras</marker> and <marker name = 'target3'>Chantigo</marker> objectives.



"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture Chantigo"];
objective3 setSimpleTaskDescription ["Capture Chantigo", "Capture Chantigo", "Capture Chantigo"];
objective2 = player createSimpleTask ["Capture Cedras"];
objective2 setSimpleTaskDescription ["Capture Cedras", "Capture Cedras", "Capture Cedras"];
objective1 = player createSimpleTask ["Capture Estrella"];
objective1 setSimpleTaskDescription ["Capture Estrella", "Capture Estrella", "Capture Estrella"];
