//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to blow stuff up.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. 
Helo <marker name = 'insert'>Insert LZ</marker> point will be on the fields NE of 
the <marker name = 'target1'>fuel depot</marker> which must be destroyed. 
Call <marker name = 'extract'>Extraction</marker> and come home.
<br/><br/>
Good luck.



<br/><br/>PMC Ranger Juice<br/><br/>

GEN SITREP<br/>
Our troops are deploying into the northern Malden, some enemy assaults have been repelled
in the airbase in past two nights. Enemy is massing some armored vehicles from the south.
<br/><br/>

INTEL<br/>
At the moment the fuel depot is readying for incomig enemy vehicles, there is no enemy armor
present but they are on their way. We have time for about one quick strike to take out the
depot until they arrive.
<br/><br/>

ORDERS<br/>
La Pessagne fuel depot is the main staging area for enemy vehicles, Alpha 
team is tasked to destroy that site. You'll <marker name = 'start'>start</marker> from base. 
UH-60 Black Hawk <marker name = 'insert'>Insert LZ</marker> point will be on the fields NE of 
the <marker name = 'target1'>fuel depot</marker> that enemy uses for refuelling and rearming. When
you have destroyed the target, use radio (0-0-1) to 
call <marker name = 'extract'>Extraction</marker> with UH-60. Mission is accomplished when any 
vehicles and fuel equipment are destroyed there and you will arrive safely at home base.
<br/><br/>

TACTICAL<br/>
Make this one fast, the enemy armored vehicles will kick your behind if they get there while
you're still on the ground.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Extract back to base"];
objective2 setSimpleTaskDescription ["Extract back to base", "Extract back to base", "Extract back to base"];
objective1 = player createSimpleTask ["Destroy fuel depot"];
objective1 setSimpleTaskDescription ["Destroy fuel depot", "Destroy fuel depot", "Destroy fuel depot"];
