//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Oh man its getting close to the finish line, it feels good!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Durras. Capture <marker name = 'target1'>Saint Pierre</marker> and <marker name = 'target2'>castle</marker> objectives.



<br/><br/>PMC Royals<br/><br/>

1. SITUATION:<br/>
As this moment our forces in southern Everon are preparing to the final push to eject the Russian army from the island of Everon. They only have last few remaining troops held up in the region and we should have no problems neutralizing them. Finally we can claim Everon ours.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Durras. Capture <marker name = 'target1'>Saint Pierre</marker> and <marker name = 'target2'>castle</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Castle"];
objective2 setSimpleTaskDescription ["Capture Castle", "Capture Castle", "Capture Castle"];
objective1 = player createSimpleTask ["Capture Saint Pierre"];
objective1 setSimpleTaskDescription ["Capture Saint Pierre", "Capture Saint Pierre", "Capture Saint Pierre"];
