//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



That's going to be interesting of hitting these targets, looking forward to it.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture the <marker name = 'target1'>Tiberia</marker>, <marker name = 'target2'>Cayo</marker> and <marker name = 'target3'>Arcadia</marker> objectives. M252 mortars have been deployed to Rahmadi and they are available under Support.



"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture Arcadia"];
objective3 setSimpleTaskDescription ["Capture Arcadia", "Capture Arcadia", "Capture Arcadia"];
objective2 = player createSimpleTask ["Capture Cayo"];
objective2 setSimpleTaskDescription ["Capture Cayo", "Capture Cayo", "Capture Cayo"];
objective1 = player createSimpleTask ["Capture Tiberia"];
objective1 setSimpleTaskDescription ["Capture Tiberia", "Capture Tiberia", "Capture Tiberia"];
