//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Without my buddies I'm nothing, well more or less. With them I can do great things, like blowing up all the enemy forces that face me. Bring it oon baby!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>base #1</marker> and <marker name = 'target2'>base #2</marker> objectives.



<br/><br/>PMC Twins<br/><br/>

1. SITUATION:<br/>
Last night we got a spike of enemy air activity, but we were able to keep them at bay. This reminds us not to let our guard down on any part of the battlefield.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>base #1</marker> and <marker name = 'target2'>base #2</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Base #2"];
objective2 setSimpleTaskDescription ["Capture Base #2", "Capture Base #2", "Capture Base #2"];
objective1 = player createSimpleTask ["Capture Base #1"];
objective1 setSimpleTaskDescription ["Capture Base #1", "Capture Base #1", "Capture Base #1"];
