//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Good morning Kolgujev, meet my team, who are here to kill all the russians, hooayh!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from shore. Capture <marker name = 'target1'>houses</marker> and <marker name = 'target2'>base</marker> objectives.
<br/><br/>



<br/><br/>PMC Rude<br/><br/>

1. SITUATION:<br/>
Today we launch our initial assault on island of Kolgujev. This will be harsh terrain to fight on, but we must take the fight to the enemy.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from shore. Capture <marker name = 'target1'>houses</marker> and <marker name = 'target2'>base</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Base"];
objective2 setSimpleTaskDescription ["Capture Base", "Capture Base", "Capture Base"];
objective1 = player createSimpleTask ["Capture Houses"];
objective1 setSimpleTaskDescription ["Capture Houses", "Capture Houses", "Capture Houses"];
