//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


One step forward and the enemy strikes back, where do they get the forces to do this, damn Russians.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Mokropsy. Defend it against <marker name = 'target1'>attack</marker> from east.



<br/><br/>PMC Ghouls<br/><br/>

1. SITUATION:<br/>
Last days for the enemy in Nogova, we are gaining grounds at heavy rate of speed. Still the enemy is launching some counterattacks in the north trying to take back what was theirs just moments before. We will continue forward until all the Russians are driven into sea.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Mokropsy. Defend it against <marker name = 'target1'>attack</marker> from east.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Todays support inlude Bravo M1A1 Abrams platoon and Charlie infantry squad. Gunship helos are fueling and rearming as we speak and join the fight ASAP.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Mokropsy"];
objective1 setSimpleTaskDescription ["Defend Mokropsy", "Defend Mokropsy", "Defend Mokropsy"];
