//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


It was a long night fighting with the ruskies, at times it got pretty scary. But after all, we won so who cares.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Le Moule. Dedend it against russian <marker name = 'target1'>counter attack</marker> from south east.



<br/><br/>PMC Badsun<br/><br/>

1. SITUATION:<br/>
This early morning we see the devastation in the La Mentin area. Enemy still keeps moving his assets to attack the region, however there only seems to be light opfor moving towards the area.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Le Moule. Dedend it against russian <marker name = 'target1'>counter attack</marker> from south east.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Bravo Black is M1A1 Abrams platoon. Charlie and Delta Black are the Mechanized infantry platoons. Echo Black is air support.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Le Moule"];
objective1 setSimpleTaskDescription ["Defend Le Moule", "Defend Le Moule", "Defend Le Moule"];
