//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


The reds seem to be quite pissed...
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Chapoi, defend it.
<br/><br/>



<br/><br/>PMC Faceslap<br/><br/>

1. SITUATION:<br/>
Enemy is on its toes now, lot of radio traffic seems to be on the air waves.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Chapoi, defend it against the russian counter attack coming from western approach.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>





"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Chapoi"];
objective1 setSimpleTaskDescription ["Defend Chapoi", "Defend Chapoi", "Defend Chapoi"];
