//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Actually I kind of like this Sahrani countryside, it reminds me of home, little bit.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Bajo Valor</marker>, <marker name = 'target2'>Valor</marker> and <marker name = 'target3'>Everon</marker> objectives.



"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture Everon"];
objective3 setSimpleTaskDescription ["Capture Everon", "Capture Everon", "Capture Everon"];
objective2 = player createSimpleTask ["Capture Valor"];
objective2 setSimpleTaskDescription ["Capture Valor", "Capture Valor", "Capture Valor"];
objective1 = player createSimpleTask ["Capture Bajo Valor"];
objective1 setSimpleTaskDescription ["Capture Bajo Valor", "Capture Bajo Valor", "Capture Bajo Valor"];
