//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Another defend mission ahead of us, how much juice the enemy has got left?
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Defend <marker name = 'defend'>main base</marker> objective.



<br/><br/>PMC Beast<br/><br/>

1. SITUATION:<br/>
Some minor offensive operations by the enemy, nothing we cant handle. Our forces are performing superbly, better than anyone could expect.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. UH60 will ferry you to the <marker name = 'lz1'>LZ</marker>, proceed to defend the <marker name = 'defend'>main base</marker> objective against Russian attack.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Your support includes M113 Ambulance standing by. Infantry squad Charlie and Mechanized infantry squad Delta, they got Bradley. AH-64 Apache gunships are loading up as we speak and join the fight ASAP.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend base"];
objective1 setSimpleTaskDescription ["Defend base", "Defend base", "Defend base"];
