//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Three days in the Nogovian soil without any support. Wonderful. But hey, thats what I'm 
trained for, thats what I do for living. I am a Ranger, all the way.<br/><br/>

So lets get a good weapons and gear selection so we are prepared for anything we might 
encounter. Lots of magazines, silenced weapons maybe if I want to avoid contact. Also we 
cant forget the anti armor equipment, we cant take down BMP with a M4 now can we.<br/><br/>

So, Nogova... here we come!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team is <marker name = 'start'>paradropped</marker> from C-130, proceed
and destroy <marker name = 'target1'>Comms Site</marker> in the hill then arrive
to the <marker name = 'gethere'>pre-set</marker> coordinates.
<br/><br/>
Good luck.



<br/><br/>PMC Ranger NoComms<br/><br/>

GEN SITREP<br/>
Today our operation to run out Russians from Nogova island begins. This will be the
biggest operation we have planned so far with joint operations from land, air and sea.
Enemy is well dug in and the elite of Russians have to offer, we are in for a fight.
<br/><br/>

INTEL<br/>
Satellite imagery suggests that the Comms site has mostly infantry presence, no armored
vehicles are in the nearby area at this time.
<br/><br/>

ORDERS<br/>
Alpha team is <marker name = 'start'>paradropped</marker> from C-130 Hercules, when you have landed 
proceed and destroy <marker name = 'target1'>Comms Site</marker> in the hill leaving no Russians
controlling it. Destroy any equipment you find in there. From there continue towards 
the <marker name = 'gethere'>pre-set</marker> coordinates in the forest where you stay for the night.
Your mission is accomplished when comms site is out and you have arrived into the forest. 
Remember that when you leap out of that C-130, you are on your own for two days. We cannot give
you any support during this time, so keep your men alive out there. The first ammo resupply you
get is when you reach for the third objective on second day in Nogova. We're looking for chance
to resupply you with C-130 ammo drop, lets hope all things work out so we get you the ammo. 
Good luck.
<br/><br/>

TACTICAL<br/>
Try to sneak in undetected in and out, get to the forest without massive Russian force on your
six. HQ's plan is to insert you guys today, then you'll be spending the night in the bush. By 
tomorrow morning you'll be proceeding to another objective. I cannot emphasize enough that you
must keep your troops alive there, dont be a hero as you have important objectives to accomplish 
and they are not including you getting killed. I'll see you again at the Nogova airbase when 
we finally assault it, until then... Stay safe and Good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Arrive to the forest"];
objective2 setSimpleTaskDescription ["Arrive to the forest", "Arrive to the forest", "Arrive to the forest"];
objective1 = player createSimpleTask ["Destroy Comms site"];
objective1 setSimpleTaskDescription ["Destroy Comms site", "Destroy Comms site", "Destroy Comms site"];
