//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Bridge demolishing, wow, this is going to be FUN!"]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from air. Assault and demolish <marker name = 'target1'>bridge 1</marker> and <marker name = 'target2'>bridge 2</marker> objectives, then <marker name = 'extract'>extract</marker> back to base.<br/><br/>PMC BoomBox<br/><br/>1. SITUATION:<br/>Enemy forces seem to be making some moves agains the positions of friendly forces.<br/><br/>2. MISSION:<br/>Destroy two bridges.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from air. You'll get inserted by blackhawk into <marker name = 'insert'>insert LZ</marker> at the beach which should be clear of enemies. Then proceed to assault and demolish <marker name = 'target1'>bridge 1</marker> and <marker name = 'target2'>bridge 2</marker> objectives, then get to <marker name = 'extract'>extract LZ</marker> back to base.<br/><br/>4. SERVICE AND SUPPORT<br/>UH60 Blackhawk is the insertion and extraction force, no other support available.<br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective3 = player createSimpleTask ["Extract"];
objective3 setSimpleTaskDescription ["Extract", "Extract", "Extract"];
objective2 = player createSimpleTask ["Demolish bridge 2"];
objective2 setSimpleTaskDescription ["Demolish bridge 2", "Demolish bridge 2", "Demolish bridge 2"];
objective1 = player createSimpleTask ["Demolish bridge 1"];
objective1 setSimpleTaskDescription ["Demolish bridge 1", "Demolish bridge 1", "Demolish bridge 1"];
