//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "Hey, this actually is working pretty good, we make good advances and the enemy doesn't seem to be match to us. I like it.<br/>"]];
player createDiaryRecord ["Diary", ["Mission", "Alpha team <marker name = 'start'>start</marker> from Provins. Capture <marker name = 'target1'>Chotain</marker> and <marker name = 'target2'>Laruns</marker> objectives.

<br/><br/>PMC Waterways<br/><br/>

1. SITUATION:<br/>
Our CAS operations seem to be effective as we start to see some armored vehicles withdraw from their positions or trying to mask their vehicles much better. Our forces have suffered only minor losses during the last couple of days of fighting.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Provins. Capture <marker name = 'target1'>Chotain</marker> and <marker name = 'target2'>Laruns</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Laruns"];
objective2 setSimpleTaskDescription ["Capture Laruns", "Capture Laruns", "Capture Laruns"];
objective1 = player createSimpleTask ["Capture Chotain"];
objective1 setSimpleTaskDescription ["Capture Chotain", "Capture Chotain", "Capture Chotain"];
