//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Welcome to Nogova, to meet the locals and save their homeland. Yeah thats me, hooyah!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from farp. Capture <marker name = 'target1'>airbase</marker> objective.



<br/><br/>PMC Transit<br/><br/>

1. SITUATION:<br/>
Today we launch our assault on the island of Nogova. It is our objective to recapture this island from the enemy forces with minimum losses of life to friendly forces. We are looking at the state of the art enemy equipment and well trained soldiers operating them. They have had time to dig in here and setup camps. Most of the civilians have fled or in hiding after the Russian invasion, so we are good to conduct our offensive operations as there is no collateral targets to worry about.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from farp. Board the UH-60 and get inserted to <marker name = 'lz1'>LZ</marker> in Nogova soil. Proceed and capture <marker name = 'target1'>airbase</marker> objective.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture airbase"];
objective1 setSimpleTaskDescription ["Capture airbase", "Capture airbase", "Capture airbase"];
