//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Those hills looks scary."]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from Arcadia. Assault and capture the <marker name = 'target1'>west</marker> and <marker name = 'target2'>east</marker> hilltops.<br/><br/>PMC Hillside<br/><br/>1. SITUATION:<br/>Enemy is alerted in the region and our forces are deeply engaged in small battles. War is going good.<br/><br/>2. MISSION:<br/>Assault and capture two hilltops.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from Arcadia. Assault and capture the <marker name = 'target1'>west</marker> and <marker name = 'target2'>east</marker> hilltops. Bravo squad is moving in from Estrella, they will hold in <marker name = 'bfup'>B FUP</marker> point for your radio (0-0-1) call for them to attack. You can call in A10 close air support with radio (0-0-2) call.<br/><br/>4. SERVICE AND SUPPORT<br/>Additional infantry squad callsign 1-1-B, AH-1 Cobra gunship is standing by in case you need CAS. Use radio (0-0-2) to call A10 close air support.<br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture hilltop 2"];
objective2 setSimpleTaskDescription ["Capture hilltop 2", "Capture hilltop 2", "Capture hilltop 2"];
objective1 = player createSimpleTask ["Capture hilltop 1"];
objective1 setSimpleTaskDescription ["Capture hilltop 1", "Capture hilltop 1", "Capture hilltop 1"];
