//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to go kill that General.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base, 
Helo <marker name = 'insert'>Insert LZ</marker> to the field then proceed 
to <marker name = 'target1'>Goisse</marker> and eliminate Russian General. 
Call <marker name = 'extract'>Extraction</marker> and return to base.



<br/><br/>PMC Ranger Decapitation<br/><br/>

GEN SITREP<br/>
Our forces continue to advance further into the island, we experience heavy 
resistance on the La Trinite area from heavy armor. By tomorrow morning we'll get
more anti armor in the area and we'll try to push through.
<br/><br/>

INTEL<br/>
We have a jackpot here. One of the POW's we captured has been interrogated and he revealed
that a genuine Russian General will be staying overnight at Goisse, thats this night. We 
believe he is still there and starts to move into some undesignated location in any minute.
<br/><br/>

ORDERS<br/>
We have information about Russian leadership on Goisse. We are running against the clock here
and every minute counts, we must immediately dispatch a team to intercept this General and
eliminate him. Alpha team <marker name = 'start'>start</marker> from airbase, 
UH-60 Black Hawk helo <marker name = 'insert'>Insert LZ</marker> to the field then proceed 
to <marker name = 'target1'>Goisse</marker> locate and eliminate the Russian General. When done,
get back to the <marker name = 'extract'>Extraction LZ</marker> and radio call (0-0-1) helo to 
bring you back to US base.
<br/><br/>

TACTICAL<br/>
No time for chit chat, get going and blow that General away, good luck.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Return to base"];
objective2 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective1 = player createSimpleTask ["Locate and neutralize Russian General"];
objective1 setSimpleTaskDescription ["Locate and neutralize Russian General", "Locate and neutralize Russian General", "Locate and neutralize Russian General"];
