//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Okay the targets are really big, wonder how it goes. Only one way to find out."]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from forest. Recon <marker name = 'target1'>Paraiso</marker>, <marker name = 'target2'>Somato</marker> and <marker name = 'target3'>Ortego</marker> objectives.<br/><br/>PMC Long Day<br/><br/>1. SITUATION:<br/>More support troops are arriving to the region, our special operations forces are conducting reconnaissance of the southern part of the Sahrani mainland. We are preparing for the first strikes against the enemy positions in the upcoming days.<br/><br/>2. MISSION:<br/>Reconnaissance of Paraiso, Somato and Ortego cities.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from forest. Recon <marker name = 'target1'>Paraiso</marker>, <marker name = 'target2'>Somato</marker> and <marker name = 'target3'>Ortego</marker> objectives. No shooting, do not fire unless fired upon. Maintain absolute covert stealth posture.<br/><br/>4. SERVICE AND SUPPORT<br/><br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective3 = player createSimpleTask ["Recon Ortego"];
objective3 setSimpleTaskDescription ["Recon Ortego", "Recon Ortego", "Recon Ortego"];
objective2 = player createSimpleTask ["Recon Somato"];
objective2 setSimpleTaskDescription ["Recon Somato", "Recon Somato", "Recon Somato"];
objective1 = player createSimpleTask ["Recon Paraiso"];
objective1 setSimpleTaskDescription ["Recon Paraiso", "Recon Paraiso", "Recon Paraiso"];
