//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




That base will be tough to take






"]];
player createDiaryRecord ["Diary", ["Mission", "


Delta team <marker name = 'start'>start</marker> from the woods, capture the
enemy <marker name = 'target1'>base</marker> and keep it secure until reinforcements arrive.



<br/><br/>PMC Ranger Baseblast<br/><br/>

GEN SITREP<br/>
We are securing foothold on Kolgujev with good success on the western part. Next objective
is offensive on enemys large base on the east coast. 
<br/><br/>

INTEL<br/>
They are expecting the attack, they are well dug in, they have patrols. There are T-80 tank
in the base but seems it will hold position there. BMP is also patrolling the area.
<br/><br/>

ORDERS<br/>
Delta team <marker name = 'start'>start</marker> from the woods, assault and capture the
enemy <marker name = 'target1'>base</marker> in the beach. When you have captured the base, we 
will send two Black Hawk to take control of the enemy base and set. When Black Hawk have 
arrived your mission is accomplished.
<br/><br/>

TACTICAL<br/>
Be careful as the enemy is well dug in now. Try to pick them off at distance and watch
the armor. Your support this time is Ranger Sniper team, they will move automatically into
position when you have crossed the ridgeline.
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture enemy base"];
objective1 setSimpleTaskDescription ["Capture enemy base", "Capture enemy base", "Capture enemy base"];
