//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Russians are attacking, man your positions boys!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Modrava. Defend if against <marker name = 'target1'>counterattack</marker> from E, NE.



<br/><br/>PMC Hunted<br/><br/>

1. SITUATION:<br/>
Enemy is trying to recapture the Modrava after our succesful strike there earlier, we must keep them away from the city at all costs. With the help of air forces we should be much more prepared to counter any enemy activity in the northern part of Nogova.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Modrava. Defend if against <marker name = 'target1'>counterattack</marker> from E, NE.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Todays support is Infantry Bravo squad and Bradley Charlie squad. AH-1 Cobra and AH-64 Apache gunships are fueling up as we speak and join the fight ASAP.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Modrava"];
objective1 setSimpleTaskDescription ["Defend Modrava", "Defend Modrava", "Defend Modrava"];
