//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


If I have to capture another set of ruins I go outta my mind. Man I need some R and R...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>ruins #1</marker> and <marker name = 'target2'>ruins #2</marker> objectives.



<br/><br/>PMC Rubble<br/><br/>

1. SITUATION:<br/>
We are now close to pushing the enemy out of Kolgujev, we must maintain the current pace to keep pressure on. We are too close to fail now. Operation continue as usual on all fronts.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>ruins #1</marker> and <marker name = 'target2'>ruins #2</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Ruins #2"];
objective2 setSimpleTaskDescription ["Capture Ruins #2", "Capture Ruins #2", "Capture Ruins #2"];
objective1 = player createSimpleTask ["Capture Ruins #1"];
objective1 setSimpleTaskDescription ["Capture Ruins #1", "Capture Ruins #1", "Capture Ruins #1"];
