
// add weaponpool for our Spec Ops
[] execVM "PMC\PMC_weaponPool.sqf";

// from earlier missions only sf1-4 exists, 5 and 6 were added on this mission!
PMC_sf1 loadStatus "pmc_sf1_arming2";
PMC_sf1 setDamage 0;
PMC_sf2 loadStatus "pmc_sf2_arming2";
PMC_sf3 loadStatus "pmc_sf3_arming2";
PMC_sf4 loadStatus "pmc_sf4_arming2";
PMC_sf5 loadStatus "pmc_sf5_arming2";
PMC_sf6 loadStatus "pmc_sf6_arming2";

{
	if (!alive _x) then
	{
		deleteVehicle _x;
	};
	_x setDamage 0;
} forEach [PMC_sf2,PMC_sf3,PMC_sf4,PMC_sf5,PMC_sf6];

[] execVM "PMC\PMC_Mission_Start.sqf";
//auto-generated by ArmaBriefingConversion

[] execVM "briefing.sqf";
