//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Time to be sneaky ninja."]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from airbase. Get <marker name = 'insert'>inserted</marker> near your objective, then <marker name = 'target1'>kill</marker> enemy officer in Ortego.<br/><br/>PMC Dead Target<br/><br/>1. SITUATION:<br/>This time there is no news from the front line.<br/><br/>2. MISSION:<br/>Find and eliminate parade uniform wearing enemy officer in Ortego.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from airbase. Get <marker name = 'insert'>inserted</marker> near your objective, then <marker name = 'target1'>kill</marker> enemy officer in Ortego. When you have accomplished your mission, proceed to be <marker name = 'extract'>extracted</marker> from the hilltop and return to <marker name = 'start'>base</marker>. Your mission will be accomplished when you have safely returned to the base.<br/><br/>4. SERVICE AND SUPPORT<br/>MH-6 will be your insertion today.<br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective2 = player createSimpleTask ["Return to base"];
objective2 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective1 = player createSimpleTask ["Find and eliminate officer"];
objective1 setSimpleTaskDescription ["Find and eliminate officer", "Find and eliminate officer", "Find and eliminate officer"];
