//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Man what a fight, and they still keep coming. Damn this war is getting tough, well grab your ammo and lets do this, I'm ready!
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Modesta</marker> and <marker name = 'target2'>Gaula</marker> objectives.



"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Gaula"];
objective2 setSimpleTaskDescription ["Capture Gaula", "Capture Gaula", "Capture Gaula"];
objective1 = player createSimpleTask ["Capture Modesta"];
objective1 setSimpleTaskDescription ["Capture Modesta", "Capture Modesta", "Capture Modesta"];
