//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Time to move on and take next town, this will be so fun."]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from Airbase. Helo insert to the <marker name = 'lz'>LZ</marker>, then proceed to assault and capture <marker name = 'target1'>Arcadia</marker> town.<br/><br/>PMC The Arc<br/><br/>1. SITUATION:<br/>Airbase is under our control and today we start to chip away enemys defenses on the southern sector of Sahrani.<br/><br/>2. MISSION:<br/>Assault and capture Arcadia.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from Airbase. Helo insert to the <marker name = 'lz'>LZ</marker>, then proceed to assault and capture <marker name = 'target1'>Arcadia</marker> town.<br/><br/>4. SERVICE AND SUPPORT<br/>Additional infantry squad callsign 1-1-B, AH-1 Cobra gunship are standing by in case you need CAS.<br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Arcadia"];
objective1 setSimpleTaskDescription ["Capture Arcadia", "Capture Arcadia", "Capture Arcadia"];
