//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Just when I thought of we getting away easy, enemy hits us with all their got. Ok bring it on ivan, I'm expecting you.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Mirov. Defend it against <marker name = 'target1'>counterattack</marker> from NW, NE and SE.



<br/><br/>PMC Workhard<br/><br/>

1. SITUATION:<br/>
Enemy has mobilized large scale attack force on the south west Nogova against our troops, we must hold the gained grounds at all cost. We are conducting some airstrikes further down the enemy supply chain to weaken their attack.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Mirov. Defend it against <marker name = 'target1'>counterattack</marker> from NW, NE and SE.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<marker name = 'ussupp'>Support</marker> forces are flowing from SW direction, so watch your fire.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Mirov"];
objective1 setSimpleTaskDescription ["Defend Mirov", "Defend Mirov", "Defend Mirov"];
