//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Okay boys, lets get ready to toast some Russians.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Blata. Dedend it against Russian <marker name = 'target1'>attack</marker> from north.



<br/><br/>PMC Flow<br/><br/>

1. SITUATION:<br/>
Our operations continue today to hit the enemy in several locations. Air striks continue on the north central area while ground forces are on defensive positions at south central. Enemy doesn't appear to have too much equipment to support the attack, but we still have to put all our efforts to stop them.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Blata. Dedend it against Russian <marker name = 'target1'>attack</marker> from north.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Bravo infantry squad is backing you up along with AH-64 Apache gunship.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Blata"];
objective1 setSimpleTaskDescription ["Defend Blata", "Defend Blata", "Defend Blata"];
