//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Uh this night shift might be interesting, would be strange if the bad guys didn't try to recapture this airstrip."]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from airstrip. Stand on watch.<br/><br/>PMC Night Shift<br/><br/>1. SITUATION:<br/>Rahmadi is held by friendly forces, so far no enemy counter attacks are detected.<br/><br/>2. MISSION:<br/>Stand on watch at the airstrip.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from airstrip. Stand on watch.<br/><br/>4. SERVICE AND SUPPORT<br/>Another infantry squad is located in the town.<br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective1 = player createSimpleTask ["Stand on watch"];
objective1 setSimpleTaskDescription ["Stand on watch", "Stand on watch", "Stand on watch"];
