//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Wonder what the enemy has awaiting for us today.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base.
capture <marker name = 'target1'>intersection</marker> objective.
capture <marker name = 'target2'>Goisse</marker> objective.



<br/><br/>PMC Regrets<br/><br/>

1. SITUATION:<br/>
Situation at the moment looks good, there are some hectic movement in the enemy side but nothing too threatening.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. proceed and 
capture <marker name = 'target1'>intersection</marker> objective.
capture <marker name = 'target2'>Goisse</marker> objective.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Goisse"];
objective2 setSimpleTaskDescription ["Capture Goisse", "Capture Goisse", "Capture Goisse"];
objective1 = player createSimpleTask ["Capture intersection"];
objective1 setSimpleTaskDescription ["Capture intersection", "Capture intersection", "Capture intersection"];
