//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Final hour ahead for the enemy. How do they take it?
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Isla Del Vassal</marker>, <marker name = 'target2'>Isla del Vida</marker>, <marker name = 'target3'>Antigua</marker> and <marker name = 'target4'>base</marker> objectives.



"]];
// tasks need to be in reversed order
objective4 = player createSimpleTask ["Capture base"];
objective4 setSimpleTaskDescription ["Capture base", "Capture base", "Capture base"];
objective3 = player createSimpleTask ["Capture Antigua"];
objective3 setSimpleTaskDescription ["Capture Antigua", "Capture Antigua", "Capture Antigua"];
objective2 = player createSimpleTask ["Capture Isla del Vida"];
objective2 setSimpleTaskDescription ["Capture Isla del Vida", "Capture Isla del Vida", "Capture Isla del Vida"];
objective1 = player createSimpleTask ["Capture Isla Del Vassal"];
objective1 setSimpleTaskDescription ["Capture Isla Del Vassal", "Capture Isla Del Vassal", "Capture Isla Del Vassal"];
