//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Big enemy counter attacks got me scared as heck. Hope the enemy keeps their distance now.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Chapoi. Assault to capture <marker name = 'target1'>La Riviere</marker> and
<marker name = 'target2'>La Pessagne</marker> objectives.
<br/><br/>



<br/><br/>PMC Gasoline<br/><br/>

1. SITUATION:<br/>
Our forces move forward and hopefully todays operation will strike a serious blow to enemys war machine.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Chapoi. Assault to capture <marker name = 'target1'>La Riviere</marker> and
<marker name = 'target2'>La Pessagne</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture La Pessagne"];
objective2 setSimpleTaskDescription ["Capture La Pessagne", "Capture La Pessagne", "Capture La Pessagne"];
objective1 = player createSimpleTask ["Capture La Riviere"];
objective1 setSimpleTaskDescription ["Capture La Riviere", "Capture La Riviere", "Capture La Riviere"];
