//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Gosh, another day and another mission.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base.
capture <marker name = 'target1'>Lany</marker> objective.
capture <marker name = 'target2'>Lipany</marker> objective.
capture <marker name = 'target3'>Okrouhlo</marker> objective.
capture <marker name = 'target4'>St. Sedlo</marker> objective.



<br/><br/>PMC Ranger Shining<br/><br/>

GEN SITREP<br/>
This is the last stand for Russians in Nogova, they have nowhere to go, this will be the 
last battle. Our forces have positioned themshelves to corner the enemy forces into the south 
east tip of the island. WMD threat has been eliminated. It will be one more day and this 
operation in Nogova is over.
<br/><br/>

INTEL<br/>
You'll be looking at infantry and armor in the area, they are still doing their usual patrols
and guarding duties.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from base. You'll get 
helo <marker name = 'insert'>insertion LZ</marker> into this location, then proceed 
and <marker name = 'meet1'>meet Hotel</marker> squad. They will start assaulting enemy positions 
with you. They back you up, you back them up. Work as a team. Mission objectives is to 
capture <marker name = 'target1'>Lany</marker> town, capture <marker name = 'target2'>Lipany</marker> city,
capture <marker name = 'target3'>Okrouhlo</marker> town and 
capture <marker name = 'target4'>St. Sedlo</marker> town. After your have achieved your objectives, 
move to the <marker name = 'extract'>extraction LZ</marker> and use radio (0-0-1) to call helicopter 
pickup. Good luck.
<br/><br/>

TACTICAL<br/>
Be sure to watch your backs out there, keep your men alive and healthy. Keep an eye for the 
Hotel squad who will join the fight. See you later on the HQ, goodspeed you all.
<br/><br/>













"]];
// tasks need to be in reversed order
objective5 = player createSimpleTask ["Return to base"];
objective5 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective4 = player createSimpleTask ["Capture St. Sedlo"];
objective4 setSimpleTaskDescription ["Capture St. Sedlo", "Capture St. Sedlo", "Capture St. Sedlo"];
objective3 = player createSimpleTask ["Capture Okrouhlo"];
objective3 setSimpleTaskDescription ["Capture Okrouhlo", "Capture Okrouhlo", "Capture Okrouhlo"];
objective2 = player createSimpleTask ["Capture Lipany"];
objective2 setSimpleTaskDescription ["Capture Lipany", "Capture Lipany", "Capture Lipany"];
objective1 = player createSimpleTask ["Capture Lany"];
objective1 setSimpleTaskDescription ["Capture Lany", "Capture Lany", "Capture Lany"];
