//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Hooyah, boots on the ground in Everon!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airbase. Defend it against <marker name = 'target1'>counter attack</marker> from south.



<br/><br/>PMC Stir 1<br/><br/>

1. SITUATION:<br/>
We have succesfully captured a foothold on island of Everon. From this point on our operations are focused on ejecting the Russian army from Everon with the minimum of friendly casualties.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from airbase. Defend it against <marker name = 'target1'>counter attack</marker> from south.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Airbase"];
objective1 setSimpleTaskDescription ["Defend Airbase", "Defend Airbase", "Defend Airbase"];
