//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


New beginning on Everon. New opportunity to kick some Russian ass!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from isle. Capture <marker name = 'target1'>airbase</marker> objective.



<br/><br/>PMC Newborn<br/><br/>

1. SITUATION:<br/>
This is the first day of Everon operations. Today we start by attacking and capturing the Everon airbase which Russians are currently holding on to.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from isle. First you get helo transported to designated <marker name = 'lz1'>LZ</marker> by the beach. When inserted, Bravo and Charlie squads sweep the <marker name = 'sup1'>houses 1</marker> and <marker name = 'sup2'>houses 2</marker> on the southern end of the runway. When they are done, they join you to assault and capture <marker name = 'target1'>airbase</marker> objective.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Bravo and Charlie squads are joining you on this initial assault. Golf Black squad is the Special Operations Forces who have secured the LZ for us this morning. They will join the fight on their own accord.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Airbase"];
objective1 setSimpleTaskDescription ["Capture Airbase", "Capture Airbase", "Capture Airbase"];
