//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Man what a fight, and they still keep coming. Night has fallen now, its dark that I cant see two feet ahead of me... and we prepare for final enemy assault. Damn this war is getting tough, well grab your ammo and lets do this, I'm ready!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airbase. Defend it against <marker name = 'target1'>counter attack</marker> from south.



<br/><br/>PMC Stir 3<br/><br/>

1. SITUATION:<br/>
We are now facing the last phase of enemy counter attack, if we can maintain our grounds now then we are free and clear to proceed further as the main enemy force here in north has been disabled.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from airbase. Defend it against <marker name = 'target1'>counter attack</marker> from south.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Airbase"];
objective1 setSimpleTaskDescription ["Defend Airbase", "Defend Airbase", "Defend Airbase"];
