//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Wonder how did I get into this mess...
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

Your forces <marker name = 'start'>start</marker> at field. Do what you do best.



"]];
// tasks need to be in reversed order
objective6 = player createSimpleTask ["Find downed helo (<marker name = 'pmc_marker_6'>posit</marker>) and rescue aircrew"];
objective6 setSimpleTaskDescription ["Find downed helo (<marker name = 'pmc_marker_6'>posit</marker>) and rescue aircrew", "Find downed helo (<marker name = 'pmc_marker_6'>posit</marker>) and rescue aircrew", "Find downed helo (<marker name = 'pmc_marker_6'>posit</marker>) and rescue aircrew"];
objective5 = player createSimpleTask ["Objective 5 (<marker name = 'pmc_marker_5'>posit</marker>)"];
objective5 setSimpleTaskDescription ["Objective 5 (<marker name = 'pmc_marker_5'>posit</marker>)", "Objective 5 (<marker name = 'pmc_marker_5'>posit</marker>)", "Objective 5 (<marker name = 'pmc_marker_5'>posit</marker>)"];
objective4 = player createSimpleTask ["Objective 4 (<marker name = 'pmc_marker_4'>posit</marker>)"];
objective4 setSimpleTaskDescription ["Objective 4 (<marker name = 'pmc_marker_4'>posit</marker>)", "Objective 4 (<marker name = 'pmc_marker_4'>posit</marker>)", "Objective 4 (<marker name = 'pmc_marker_4'>posit</marker>)"];
objective3 = player createSimpleTask ["Objective 3 (<marker name = 'pmc_marker_3'>posit</marker>)"];
objective3 setSimpleTaskDescription ["Objective 3 (<marker name = 'pmc_marker_3'>posit</marker>)", "Objective 3 (<marker name = 'pmc_marker_3'>posit</marker>)", "Objective 3 (<marker name = 'pmc_marker_3'>posit</marker>)"];
objective2 = player createSimpleTask ["Objective 2 (<marker name = 'pmc_marker_2'>posit</marker>)"];
objective2 setSimpleTaskDescription ["Objective 2 (<marker name = 'pmc_marker_2'>posit</marker>)", "Objective 2 (<marker name = 'pmc_marker_2'>posit</marker>)", "Objective 2 (<marker name = 'pmc_marker_2'>posit</marker>)"];
objective1 = player createSimpleTask ["Objective 1 (<marker name = 'pmc_marker_1'>posit</marker>)"];
objective1 setSimpleTaskDescription ["Objective 1 (<marker name = 'pmc_marker_1'>posit</marker>)", "Objective 1 (<marker name = 'pmc_marker_1'>posit</marker>)", "Objective 1 (<marker name = 'pmc_marker_1'>posit</marker>)"];
