//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


That airbase looks scary, so heavy defenses.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> near Larche. Proceed to attack <marker name = 'target1'>airbase</marker> and <marker name = 'target2'>fuel depot</marker> objectives.
<br/><br/>



<br/><br/>PMC Airwave<br/><br/>

1. SITUATION:<br/>
Our objectives are almost complete in Malden island, there is still heavy enemy forces present in the northern tip, but today we hopefull gain upper hand o nthem.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> near Larche. Proceed to attack <marker name = 'target1'>airbase</marker> and <marker name = 'target2'>fuel depot</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Fuel depot"];
objective2 setSimpleTaskDescription ["Capture Fuel depot", "Capture Fuel depot", "Capture Fuel depot"];
objective1 = player createSimpleTask ["Capture Airbase"];
objective1 setSimpleTaskDescription ["Capture Airbase", "Capture Airbase", "Capture Airbase"];
