//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Okay boys, lets get ready to toast some SLA.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Hunapu</marker> and <marker name = 'target2'>base</marker> objectives.



"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture base"];
objective2 setSimpleTaskDescription ["Capture base", "Capture base", "Capture base"];
objective1 = player createSimpleTask ["Capture Hunapu"];
objective1 setSimpleTaskDescription ["Capture Hunapu", "Capture Hunapu", "Capture Hunapu"];
