//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Oh no, graveyard patrol, well thats going to be chilly...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Patrol <marker name = 'target1'>ruins</marker> and <marker name = 'target2'>graveyard</marker> objectives.



<br/><br/>PMC Graves<br/><br/>

1. SITUATION:<br/>
Enemy was not expecting us, we got a foothold on Kolgujev. Our forces start to deploy now on to the south Kolgujev in order to proceed further on the island.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. Wait for Bravo to arrive on UH-60, when they are present start your mission which is to patrol <marker name = 'target1'>ruins</marker> and <marker name = 'target2'>graveyard</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Bravo Black squad will handle base security.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Patrol graveyard"];
objective2 setSimpleTaskDescription ["Patrol graveyard", "Patrol graveyard", "Patrol graveyard"];
objective1 = player createSimpleTask ["Patrol ruins"];
objective1 setSimpleTaskDescription ["Patrol ruins", "Patrol ruins", "Patrol ruins"];
