//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Wonder what the enemy has awaiting for us today.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture the <marker name = 'target1'>Iguana</marker> and <marker name = 'target2'>Parato</marker> objectives. 



"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Parato"];
objective2 setSimpleTaskDescription ["Capture Parato", "Capture Parato", "Capture Parato"];
objective1 = player createSimpleTask ["Capture Iguana"];
objective1 setSimpleTaskDescription ["Capture Iguana", "Capture Iguana", "Capture Iguana"];
