//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Wonder how my parents feels back home as I'm fighting this war far away.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Eponia</marker>, <marker name = 'target2'>Tlaloc</marker> and <marker name = 'target3'>intersection</marker> objectives.



"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture intersection"];
objective3 setSimpleTaskDescription ["Capture intersection", "Capture intersection", "Capture intersection"];
objective2 = player createSimpleTask ["Capture Tlaloc"];
objective2 setSimpleTaskDescription ["Capture Tlaloc", "Capture Tlaloc", "Capture Tlaloc"];
objective1 = player createSimpleTask ["Capture Eponia"];
objective1 setSimpleTaskDescription ["Capture Eponia", "Capture Eponia", "Capture Eponia"];
