//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Actually I kind of like this Everon countryside, it reminds me of home, little bit.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Meaux. Capture <marker name = 'target1'>Tyrone</marker> and <marker name = 'target2'>Gravette</marker> objectives.



<br/><br/>PMC Sparrow<br/><br/>

1. SITUATION:<br/>
We are seeing some suspicious movement by the enemy forces which we are keeping close eye into. Our Special Operations Forces are reporting some interesting activity from behind the frontline. As we speak our forces are preparing for another push towards south.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Meaux. Capture <marker name = 'target1'>Tyrone</marker> and <marker name = 'target2'>Gravette</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Gravette"];
objective2 setSimpleTaskDescription ["Capture Gravette", "Capture Gravette", "Capture Gravette"];
objective1 = player createSimpleTask ["Capture Tyrone"];
objective1 setSimpleTaskDescription ["Capture Tyrone", "Capture Tyrone", "Capture Tyrone"];
