//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Time to bust some heads.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

Special Forces <marker name = 'start'>start</marker> at Rahmadi. Defend it against enemy counter attack. When the attacks have been repelled, use radio (0-0-1) to call HQ.



"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Rahmadi"];
objective1 setSimpleTaskDescription ["Defend Rahmadi", "Defend Rahmadi", "Defend Rahmadi"];
