//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Its another day and another mission, all in goof fun today.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins. Capture <marker name = 'target1'>base #1</marker> and <marker name = 'target2'>base #2</marker> objectives.



<br/><br/>PMC Homeplate<br/><br/>

1. SITUATION:<br/>
Enemy has got to be starting to feel the pressure by now, we move on them without mercy on all fronts and it got to be hurting.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from ruins. Capture <marker name = 'target1'>base #1</marker> and <marker name = 'target2'>base #2</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Base #2"];
objective2 setSimpleTaskDescription ["Capture Base #2", "Capture Base #2", "Capture Base #2"];
objective1 = player createSimpleTask ["Capture Base #1"];
objective1 setSimpleTaskDescription ["Capture Base #1", "Capture Base #1", "Capture Base #1"];
