//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Rangers lead the way, All the Way!

<br/>






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from W of the target, assault it
and <marker name = 'target1'>capture</marker> the city.



<br/><br/>PMC Ranger Action<br/><br/>

GEN SITREP<br/>
Rangers are taking on the Russian positions in NW Kolgujev today, all other forces
should keep a distance until Rangers have cleared and secured the city.
<br/><br/>

INTEL<br/>
We estimate that there is two squads plus some additional infantry present in the target
city, also some vehicles have been spotted. Armor are mostly based further into east.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> just west from todays target objective. Your task
is to assault the objective city and <marker name = 'target1'>capture</marker> from the Russians.
Mission is accomplished when you have control over the city.
<br/><br/>

TACTICAL<br/>
There are only few vehicles present so this would be mostly infantry fight today. Stay alert
for any reinforcements though, they would come from eastern direction. Rangers lead the way, 
Hooyah!
<br/><br/>













"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture city ruins"];
objective1 setSimpleTaskDescription ["Capture city ruins", "Capture city ruins", "Capture city ruins"];
