//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



I get funny feeling about this one, maybe the enemy has something special awaiting for us today, so I guess its better to keep my act tight.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture the <marker name = 'target1'>Corazol</marker> south side. Do not proceed north side of the town. Today your MLRS rocket system arrived, its available under support.



"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Corazol south side"];
objective1 setSimpleTaskDescription ["Capture Corazol south side", "Capture Corazol south side", "Capture Corazol south side"];
