//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Good morning Sahrani, meet my team, who are here to kill all of the enemy, hooayh!
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Vallejo</marker>, <marker name = 'target2'>hilltop</marker> and <marker name = 'target3'>San Peregrino</marker> objectives.



"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture San Peregrino"];
objective3 setSimpleTaskDescription ["Capture San Peregrino", "Capture San Peregrino", "Capture San Peregrino"];
objective2 = player createSimpleTask ["Capture hilltop"];
objective2 setSimpleTaskDescription ["Capture hilltop", "Capture hilltop", "Capture hilltop"];
objective1 = player createSimpleTask ["Capture Vallejo"];
objective1 setSimpleTaskDescription ["Capture Vallejo", "Capture Vallejo", "Capture Vallejo"];
