//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


That was some long night, long battle. I'm tired...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Montignac. Capture <marker name = 'target1'>Entre Deux</marker>, <marker name = 'target2'>farmhouses</marker> and <marker name = 'target3'>coastal base</marker> objectives.



<br/><br/>PMC Rider<br/><br/>

1. SITUATION:<br/>
Enemy counterattack in central Everon was stopped by our forces. Right now we must push forward and not let enemy consolidate their positions too much.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Montignac. Capture <marker name = 'target1'>Entre Deux</marker>, <marker name = 'target2'>farmhouses</marker> and <marker name = 'target3'>coastal base</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Farmhouses"];
objective2 setSimpleTaskDescription ["Capture Farmhouses", "Capture Farmhouses", "Capture Farmhouses"];
objective1 = player createSimpleTask ["Capture Entre Deux"];
objective1 setSimpleTaskDescription ["Capture Entre Deux", "Capture Entre Deux", "Capture Entre Deux"];
