//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Time to move forward again, I love this stuff so much. Lets bring the fight to the enemy!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>base</marker> objective.



<br/><br/>PMC Lowdown<br/><br/>

1. SITUATION:<br/>
The latest offensive was medicore at best, our forces hold their grounds. Now we are looking ways into disrupting enemy supply system as that might further reduce their ability to fight.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>base</marker> objective.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Capture Base"];
objective1 setSimpleTaskDescription ["Capture Base", "Capture Base", "Capture Base"];
