//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


My squad looks confident, I see nobody having any doubts of the upcoming missions, thats always good.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from airbase. Capture <marker name = 'target1'>base</marker> and <marker name = 'target2'>Mirov</marker> objectives.



<br/><br/>PMC Hardwork<br/><br/>

1. SITUATION:<br/>
We have now strong foothold on the island of Nogova, our forces have arrived here in numbers and we can now held onto the airbase to keep the lifeline open. Today we push forward north east towards the enemy strongholds.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from airbase. Capture <marker name = 'target1'>base</marker> and <marker name = 'target2'>Mirov</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Mirov"];
objective2 setSimpleTaskDescription ["Capture Mirov", "Capture Mirov", "Capture Mirov"];
objective1 = player createSimpleTask ["Capture base"];
objective1 setSimpleTaskDescription ["Capture base", "Capture base", "Capture base"];
