//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


South is going to fall baby!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Lany. Capture <marker name = 'target1'>Lipany</marker>, <marker name = 'target2'>Okrouhlo</marker> and <marker name = 'target3'>St. Sedlo</marker> objectives.



<br/><br/>PMC Southstate<br/><br/>

1. SITUATION:<br/>
Today we launch operation to capture the remainders of the terrain in south east Nogova. By this rate tomorrow, we can claim the whole southern Nogova ours. Enemy looks like they are fortificating their positions up north, so we might excpect to see must stronger resistance in the upcoming days.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Lany. Capture <marker name = 'target1'>Lipany</marker>, <marker name = 'target2'>Okrouhlo</marker> and <marker name = 'target3'>St. Sedlo</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Todays support includes Bradley squad, M1A1 Abrams platoon, AH-1 Cobra, AH-64 Apache gunships and A-10 tank killer.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture St. Sedlo"];
objective3 setSimpleTaskDescription ["Capture St. Sedlo", "Capture St. Sedlo", "Capture St. Sedlo"];
objective2 = player createSimpleTask ["Capture Okrouhlo"];
objective2 setSimpleTaskDescription ["Capture Okrouhlo", "Capture Okrouhlo", "Capture Okrouhlo"];
objective1 = player createSimpleTask ["Capture Lipany"];
objective1 setSimpleTaskDescription ["Capture Lipany", "Capture Lipany", "Capture Lipany"];
