//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


I have that funny feeling about todays mission, I dont know why, I just do.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>Chapoi</marker> and <marker name = 'target2'>Cancon</marker> objectives.
<br/><br/>



<br/><br/>PMC Champion<br/><br/>

1. SITUATION:<br/>
Operations are in good start now, we will continue forward as planned to keep the enemy on their toes.
<br/><br/>

2. MISSION:<br/>
Chapoi and Cancon are the next western most populated areas from the captured territory we hold. Todays objectives include to capture these towns from the enemy froces.
<br/><br/>

3. EXECUTION:<br/>
Three infantry squads <marker name = 'start'>start</marker> from base. Helicopter insert at designated <marker name = 'lz'>LZ</marker> in the fields. Assault and capture <marker name = 'target1'>Chapoi</marker> and <marker name = 'target2'>Cancon</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
AH-1 Cobra gunships join to support your attack, they should neutralize all armor you encounter.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>





"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Cancon"];
objective2 setSimpleTaskDescription ["Capture Cancon", "Capture Cancon", "Capture Cancon"];
objective1 = player createSimpleTask ["Capture Chapoi"];
objective1 setSimpleTaskDescription ["Capture Chapoi", "Capture Chapoi", "Capture Chapoi"];
