
pmc_ammobox_fobghoul_1 saveStatus "PMC_StatusAmmoBoxFOBGhoul_1";
pmc_ammobox_fobghoul_2 saveStatus "PMC_StatusAmmoBoxFOBGhoul_2";
pmc_ammobox_fobghoul_3 saveStatus "PMC_StatusAmmoBoxFOBGhoul_3";
pmc_ammobox_fobghoul_4 saveStatus "PMC_StatusAmmoBoxFOBGhoul_4";
pmc_ammobox_fobghoul_5 saveStatus "PMC_StatusAmmoBoxFOBGhoul_5";
pmc_ammobox_fobghoul_6 saveStatus "PMC_StatusAmmoBoxFOBGhoul_6";
pmc_ammobox_fobghoul_7 saveStatus "PMC_StatusAmmoBoxFOBGhoul_7";
pmc_ammobox_fobghoul_8 saveStatus "PMC_StatusAmmoBoxFOBGhoul_8";
