
pmc_ammobox_fobfalcon_1 saveStatus "PMC_StatusAmmoBoxFOBFalcon_1";
pmc_ammobox_fobfalcon_2 saveStatus "PMC_StatusAmmoBoxFOBFalcon_2";
pmc_ammobox_fobfalcon_3 saveStatus "PMC_StatusAmmoBoxFOBFalcon_3";
pmc_ammobox_fobfalcon_4 saveStatus "PMC_StatusAmmoBoxFOBFalcon_4";
pmc_ammobox_fobfalcon_5 saveStatus "PMC_StatusAmmoBoxFOBFalcon_5";
pmc_ammobox_fobfalcon_6 saveStatus "PMC_StatusAmmoBoxFOBFalcon_6";
pmc_ammobox_fobfalcon_7 saveStatus "PMC_StatusAmmoBoxFOBFalcon_7";
