
pmc_ammobox_fobeagle_1 loadStatus "PMC_StatusAmmoBoxFOBEagle_1";
pmc_ammobox_fobeagle_2 loadStatus "PMC_StatusAmmoBoxFOBEagle_2";
pmc_ammobox_fobeagle_3 loadStatus "PMC_StatusAmmoBoxFOBEagle_3";
pmc_ammobox_fobeagle_4 loadStatus "PMC_StatusAmmoBoxFOBEagle_4";
pmc_ammobox_fobeagle_5 loadStatus "PMC_StatusAmmoBoxFOBEagle_5";
pmc_ammobox_fobeagle_6 loadStatus "PMC_StatusAmmoBoxFOBEagle_6";
