
pmc_ammobox_fobeagle_1 saveStatus "PMC_StatusAmmoBoxFOBEagle_1";
pmc_ammobox_fobeagle_2 saveStatus "PMC_StatusAmmoBoxFOBEagle_2";
pmc_ammobox_fobeagle_3 saveStatus "PMC_StatusAmmoBoxFOBEagle_3";
pmc_ammobox_fobeagle_4 saveStatus "PMC_StatusAmmoBoxFOBEagle_4";
pmc_ammobox_fobeagle_5 saveStatus "PMC_StatusAmmoBoxFOBEagle_5";
pmc_ammobox_fobeagle_6 saveStatus "PMC_StatusAmmoBoxFOBEagle_6";
pmc_ammobox_fobeagle_7 saveStatus "PMC_StatusAmmoBoxFOBEagle_7";
pmc_ammobox_fobeagle_8 saveStatus "PMC_StatusAmmoBoxFOBEagle_8";
