
pmc_ammobox_campmaxwell_3 saveStatus "PMC_StatusAmmoBoxCampMaxwell_3";
pmc_ammobox_campmaxwell_4 saveStatus "PMC_StatusAmmoBoxCampMaxwell_4";
pmc_ammobox_campmaxwell_5 saveStatus "PMC_StatusAmmoBoxCampMaxwell_5";
pmc_ammobox_campmaxwell_6 saveStatus "PMC_StatusAmmoBoxCampMaxwell_6";
pmc_ammobox_campmaxwell_7 saveStatus "PMC_StatusAmmoBoxCampMaxwell_7";
pmc_ammobox_campmaxwell_8 saveStatus "PMC_StatusAmmoBoxCampMaxwell_8";
