
pmc_ammobox_fobraven_1 loadStatus "PMC_StatusAmmoBoxFOBRaven_1";
pmc_ammobox_fobraven_2 loadStatus "PMC_StatusAmmoBoxFOBRaven_2";
pmc_ammobox_fobraven_3 loadStatus "PMC_StatusAmmoBoxFOBRaven_3";
pmc_ammobox_fobraven_4 loadStatus "PMC_StatusAmmoBoxFOBRaven_4";
pmc_ammobox_fobraven_5 loadStatus "PMC_StatusAmmoBoxFOBRaven_5";
pmc_ammobox_fobraven_6 loadStatus "PMC_StatusAmmoBoxFOBRaven_6";
