
pmc_ammobox_fobfalcon_1 loadStatus "PMC_StatusAmmoBoxFOBFalcon_1";
pmc_ammobox_fobfalcon_2 loadStatus "PMC_StatusAmmoBoxFOBFalcon_2";
pmc_ammobox_fobfalcon_3 loadStatus "PMC_StatusAmmoBoxFOBFalcon_3";
pmc_ammobox_fobfalcon_4 loadStatus "PMC_StatusAmmoBoxFOBFalcon_4";
pmc_ammobox_fobfalcon_5 loadStatus "PMC_StatusAmmoBoxFOBFalcon_5";
pmc_ammobox_fobfalcon_6 loadStatus "PMC_StatusAmmoBoxFOBFalcon_6";
pmc_ammobox_fobfalcon_7 loadStatus "PMC_StatusAmmoBoxFOBFalcon_7";
