
// weaponPool init, add some good US stuff

diag_log format ["PMC_WeaponPoolInit ran from %1 at %2 seconds", missionName, time];
/*
confirmed working 2018-09-03. But do note that this list is TOO LONG to be added from init.sqf into briefing -> team -> inventory.
you must use "weaponPool init mission" so the added stuff shows up on NEXT missions inventory.
solution: use ammo boxex, man ... :(
*/
{
	addWeaponPool ["CUP_srifle_M14_DMR_LeupoldMk4", _x];
	addWeaponPool ["CUP_arifle_M16A4_GL", _x];
	addWeaponPool ["CUP_arifle_M16A4_Aim_Laser", _x];
	addWeaponPool ["CUP_arifle_M4A1_Aim_Laser_snds", _x];
	addWeaponPool ["CUP_arifle_M4A1_camo_AIM_snds", _x];
	addWeaponPool ["CUP_arifle_M4A1_camo_GL_Holo_Flashlight", _x];
	addWeaponPool ["CUP_arifle_M4A1_camo_GL_Holo_Flashlight_Snds", _x];
	addWeaponPool ["CUP_arifle_M4A1_M203_ACOG_Laser", _x];
	addWeaponPool ["CUP_arifle_M4A1_M203_Holo_Laser", _x];
	addWeaponPool ["CUP_arifle_Mk17_STD_FG_Aim_Laser_snds", _x];
	addWeaponPool ["CUP_arifle_Mk17_STD_FG_ANPAS13c1_Laser_Snds", _x];
	addWeaponPool ["CUP_arifle_Mk20_LeupoldMk4MRT", _x];
	addWeaponPool ["CUP_arifle_Mk20_SB11420_snds", _x];
	addWeaponPool ["CUP_hgun_Colt1911", _x];
	addWeaponPool ["CUP_hgun_Colt1911_snds", _x];
	addWeaponPool ["CUP_arifle_G36A", _x];
	addWeaponPool ["CUP_arifle_G36C", _x];
	addWeaponPool ["CUP_arifle_G36C_camo_holo_snds", _x];
	addWeaponPool ["CUP_arifle_G36K", _x];
	addWeaponPool ["CUP_arifle_XM8_Carbine", _x];
	addWeaponPool ["CUP_arifle_XM8_Carbine_GL", _x];
	addWeaponPool ["CUP_arifle_XM8_Compact", _x];
	addWeaponPool ["CUP_arifle_xm8_sharpshooter", _x];
	addWeaponPool ["CUP_hgun_Duty", _x];
	addWeaponPool ["CUP_hgun_Duty_M3X", _x];
	addWeaponPool ["CUP_hgun_Glock17", _x];
	addWeaponPool ["CUP_hgun_glock17_snds", _x];
	addWeaponPool ["CUP_hgun_M9_snds", _x];
	addWeaponPool ["CUP_hgun_Phantom_Flashlight_snds", _x];
	addWeaponPool ["CUP_huntingrifle", _x];
	addWeaponPool ["CUP_Laserdesignator", _x];
	addWeaponPool ["CUP_launch_FIM92Stinger", _x];
	addWeaponPool ["CUP_launch_Igla", _x];
	addWeaponPool ["CUP_launch_Javelin", _x];
	addWeaponPool ["CUP_launch_M136", _x];
	addWeaponPool ["CUP_launch_Mk153Mod0_SMAWOptics", _x];
	addWeaponPool ["Binocular", _x];
	addWeaponPool ["CUP_lmg_M249", _x];
	addWeaponPool ["CUP_lmg_M60E4", _x];
	addWeaponPool ["CUP_lmg_Mk48_wdl_Aim_Laser", _x];
	addWeaponPool ["CUP_M107", _x];
	addWeaponPool ["CUP_M16A2", _x];
	addWeaponPool ["CUP_M16A2GL", _x];
	addWeaponPool ["CUP_M16A4", _x];
	addWeaponPool ["CUP_m16a4_acg", _x];
	addWeaponPool ["CUP_M16A4_ACG_GL", _x];
	addWeaponPool ["CUP_M16A4_GL", _x];
	addWeaponPool ["CUP_M240", _x];
	addWeaponPool ["CUP_M40A3", _x];
	addWeaponPool ["CUP_M4A1", _x];
	addWeaponPool ["CUP_M4A1_Aim", _x];
	addWeaponPool ["CUP_M4A1_Aim_camo", _x];
	addWeaponPool ["CUP_M4A1_AIM_SD_camo", _x];
	addWeaponPool ["CUP_M4SPR", _x];
	addWeaponPool ["CUP_m8_SAW", _x];
	addWeaponPool ["CUP_M9", _x];
	addWeaponPool ["CUP_M9SD", _x];
	addWeaponPool ["CUP_MG36", _x];
	addWeaponPool ["CUP_smg_MP5A5", _x];
	addWeaponPool ["CUP_smg_MP5SD6", _x];
	addWeaponPool ["CUP_srifle_CZ550", _x];
	addWeaponPool ["CUP_srifle_CZ550_rail", _x];
	addWeaponPool ["CUP_srifle_CZ750", _x];
	addWeaponPool ["CUP_srifle_CZ750_SOS_bipod", _x];
	addWeaponPool ["CUP_NVG_HMNVS", _x];
	addWeaponPool ["CUP_NVG_PVS7", _x];
	addWeaponPool ["CUP_NVG_PVS14", _x];
	addWeaponPool ["CUP_srifle_M107_ANPAS13c2", _x];
	addWeaponPool ["CUP_srifle_M107_LeupoldVX3", _x];
	addWeaponPool ["CUP_srifle_M110", _x];
	addWeaponPool ["CUP_srifle_M110_ANPAS13c2", _x];
	addWeaponPool ["CUP_srifle_M110_ANPVS10", _x];
	addWeaponPool ["CUP_srifle_M24_ghillie", _x];
	addWeaponPool ["CUP_srifle_M24_wdl", _x];
	addWeaponPool ["CUP_srifle_M24_wdl_LeupoldMk4LRT", _x];
	addWeaponPool ["CUP_srifle_M40A3", _x];
	addWeaponPool ["CUP_srifle_Mk12SPR_LeupoldM3LR", _x];
	addWeaponPool ["CUP_srifle_Mk12SPR_LeupoldM3LR_bipod", _x];

	addMagazinePool ["CUP_100Rnd_556x45_BetaCMag", (_x * 20)];
	addMagazinePool ["CUP_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M", (_x * 20)];
	addMagazinePool ["CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M", (_x * 20)];
	addMagazinePool ["CUP_10Rnd_127x99_M107", (_x * 20)];
	addMagazinePool ["CUP_10Rnd_762x51_CZ750", (_x * 20)];
	addMagazinePool ["CUP_10Rnd_762x51_CZ750_Tracer", (_x * 20)];
	addMagazinePool ["CUP_15Rnd_9x19_M9", (_x * 20)];
	addMagazinePool ["CUP_17Rnd_9x19_glock17", (_x * 20)];
	addMagazinePool ["CUP_18Rnd_9x19_Phantom", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_HE_M203", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_HEDP_M203", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_StarCluster_Green_M203", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_StarCluster_Red_M203", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_StarCluster_White_M203", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_StarFlare_Green_M203", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_StarFlare_Red_M203", (_x * 20)];
	addMagazinePool ["CUP_1Rnd_StarFlare_White_M203", (_x * 20)];
	addMagazinePool ["CUP_200Rnd_TE4_Red_Tracer_556x45_M249", (_x * 20)];
	addMagazinePool ["CUP_20Rnd_556x45_Stanag", (_x * 20)];
	addMagazinePool ["CUP_20Rnd_762x51_B_M110", (_x * 20)];
	addMagazinePool ["CUP_20Rnd_762x51_B_SCAR", (_x * 20)];
	addMagazinePool ["CUP_30Rnd_556x45_G36", (_x * 20)];
	addMagazinePool ["CUP_30Rnd_9x19_MP5", (_x * 20)];
	addMagazinePool ["CUP_5Rnd_762x51_M24", (_x * 20)];
	addMagazinePool ["CUP_5x_22_LR_17_HMR_M", (_x * 20)];
	addMagazinePool ["CUP_7Rnd_45ACP_1911", (_x * 20)];
	addMagazinePool ["CUP_FlareGreen_M203",(_x * 20)];
	addMagazinePool ["CUP_FlareRed_M203",(_x * 20)];
	addMagazinePool ["CUP_FlareWhite_M203",(_x * 20)];
	addMagazinePool ["CUP_FlareYellow_M203",(_x * 20)];
	addMagazinePool ["CUP_HandGrenade_M67", (_x * 20)];
	addMagazinePool ["CUP_Igla_M", (_x * 20)];
	addMagazinePool ["CUP_Javelin_M", (_x * 20)];
	addMagazinePool ["CUP_M136_M", (_x * 20)];
	addMagazinePool ["CUP_Mine_M", (_x * 20)]; // AT-15 anti tank mine
	addMagazinePool ["CUP_PipeBomb_M", (_x * 20)]; // satchel charge
	addMagazinePool ["CUP_SMAW_HEAA_M", (_x * 20)];
	addMagazinePool ["CUP_SMAW_HEDP_M", (_x * 20)];
	addMagazinePool ["CUP_Stinger_M", (_x * 20)];
	addMagazinePool ["CUP_TimeBomb_M", (_x * 20)];
	addMagazinePool ["Laserbatteries", (_x * 20)];
	addMagazinePool ["SmokeShell", (_x * 20)];
	addMagazinePool ["SmokeShellGreen", (_x * 20)];
	addMagazinePool ["SmokeShellRed", (_x * 20)];
	addMagazinePool ["CUP_20Rnd_762x51_DMR", (_x * 20)];
	addMagazinePool ["CUP_30Rnd_556x45_Stanag", (_x * 20)];

	addItemPool ["CUP_acc_ANPEQ_15", _x];
	addItemPool ["CUP_acc_ANPEQ_2", _x];
	addItemPool ["CUP_acc_ANPEQ_2_camo", _x];
	addItemPool ["CUP_acc_ANPEQ_2_desert", _x];
	addItemPool ["CUP_acc_ANPEQ_2_grey", _x];
	addItemPool ["CUP_acc_Flashlight", _x];
	addItemPool ["CUP_acc_Flashlight_desert", _x];
	addItemPool ["CUP_acc_Flashlight_wdl", _x];
	addItemPool ["CUP_acc_LLM", _x];
	addItemPool ["CUP_acc_XM8_light_module", _x];
	addItemPool ["CUP_bipod_Harris_1A2_L", _x];
	addItemPool ["CUP_bipod_VLTOR_Modpod", _x];
	addItemPool ["CUP_muzzle_mfsup_SCAR_L", _x];
	addItemPool ["CUP_muzzle_snds_M110", _x];
	addItemPool ["CUP_muzzle_snds_M14", _x];
	addItemPool ["CUP_muzzle_snds_M16", _x];
	addItemPool ["CUP_muzzle_snds_M16_camo", _x];
	addItemPool ["CUP_muzzle_snds_M9", _x];
	addItemPool ["CUP_muzzle_snds_Mk12", _x];
	addItemPool ["CUP_muzzle_snds_SCAR_H", _x];
	addItemPool ["CUP_muzzle_snds_SCAR_L", _x];
	addItemPool ["CUP_optic_ACOG", _x];
	addItemPool ["CUP_optic_AN_PAS_13c1", _x];
	addItemPool ["CUP_optic_AN_PAS_13c2", _x];
	addItemPool ["CUP_optic_AN_PVS_10", _x];
	addItemPool ["CUP_optic_AN_PVS_4", _x];
	addItemPool ["CUP_optic_CompM2_Black", _x];
	addItemPool ["CUP_optic_CompM2_Desert", _x];
	addItemPool ["CUP_optic_CompM2_Woodland", _x];
	addItemPool ["CUP_optic_CompM2_Woodland2", _x];
	addItemPool ["CUP_optic_CompM4", _x];
	addItemPool ["CUP_optic_CWS", _x];
	addItemPool ["CUP_optic_Elcan", _x];
	addItemPool ["CUP_optic_Elcan_reflex", _x];
	addItemPool ["CUP_optic_ELCAN_SpecterDR", _x];
	addItemPool ["CUP_optic_ElcanM145", _x];
	addItemPool ["CUP_optic_Eotech533", _x];
	addItemPool ["CUP_optic_Eotech533Grey", _x];
	addItemPool ["CUP_optic_HoloBlack", _x];
	addItemPool ["CUP_optic_HoloDesert", _x];
	addItemPool ["CUP_optic_HoloWdl", _x];
	addItemPool ["CUP_optic_Leupold_VX3", _x];
	addItemPool ["CUP_optic_LeupoldM3LR", _x];
	addItemPool ["CUP_optic_LeupoldMk4", _x];
	addItemPool ["CUP_optic_LeupoldMk4_10x40_LRT_Desert", _x];
	addItemPool ["CUP_optic_LeupoldMk4_10x40_LRT_Woodland", _x];
	addItemPool ["CUP_optic_LeupoldMk4_CQ_T", _x];
	addItemPool ["CUP_optic_LeupoldMk4_MRT_tan", _x];
	addItemPool ["CUP_optic_MRad", _x];
	addItemPool ["CUP_optic_RCO", _x];
	addItemPool ["CUP_optic_RCO_desert", _x];
	addItemPool ["CUP_optic_SB_11_4x20_PM", _x];
	addItemPool ["CUP_optic_SB_3_12x50_PMII", _x];
	addItemPool ["CUP_optic_SUSAT", _x];
	addItemPool ["CUP_optic_TrijiconRx01_black", _x];
	addItemPool ["CUP_optic_TrijiconRx01_desert", _x];
	addItemPool ["CUP_optic_ZDDot", _x];
} forEach [1];
