//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Hear the silence? I don't. I hear gunfire, explosions, screams and suffering. Hooayh! all caused by my troops, lets go and do some more damage!
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Capture <marker name = 'target1'>Obregan</marker> and <marker name = 'target2'>Mercalillo</marker> objectives.



"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Enemy forces are spotted advancing from Masbete towards Pita, your new orders are to <marker name = 'target3'>defend Pita!</marker> at all cost. However DO NOT ENTER INTO ENEMY TERRITORY, so keep your ground vehicles at near Obregan and Mercalillo. Do not overfly the keep out area either, air assault from above the sea. Good luck."];
objective3 setSimpleTaskDescription ["Enemy forces are spotted advancing from Masbete towards Pita, your new orders are to <marker name = 'target3'>defend Pita!</marker> at all cost. However DO NOT ENTER INTO ENEMY TERRITORY, so keep your ground vehicles at near Obregan and Mercalillo. Do not overfly the keep out area either, air assault from above the sea. Good luck.", "Enemy forces are spotted advancing from Masbete towards Pita, your new orders are to <marker name = 'target3'>defend Pita!</marker> at all cost. However DO NOT ENTER INTO ENEMY TERRITORY, so keep your ground vehicles at near Obregan and Mercalillo. Do not overfly the keep out area either, air assault from above the sea. Good luck.", "Enemy forces are spotted advancing from Masbete towards Pita, your new orders are to <marker name = 'target3'>defend Pita!</marker> at all cost. However DO NOT ENTER INTO ENEMY TERRITORY, so keep your ground vehicles at near Obregan and Mercalillo. Do not overfly the keep out area either, air assault from above the sea. Good luck."];
objective2 = player createSimpleTask ["Capture Mercalillo"];
objective2 setSimpleTaskDescription ["Capture Mercalillo", "Capture Mercalillo", "Capture Mercalillo"];
objective1 = player createSimpleTask ["Capture Obregan"];
objective1 setSimpleTaskDescription ["Capture Obregan", "Capture Obregan", "Capture Obregan"];
