//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Big battle in Modrava, I consider myself lucky that I survived it, many guys didnt...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Modrova. Capture <marker name = 'target1'>Opatov</marker>, meet M1A1 Platoon, then capture <marker name = 'target2'>village</marker>, <marker name = 'target3'>Dolina</marker> and <marker name = 'target4'>Mokropsy</marker> objectives.



<br/><br/>PMC Rockyroad<br/><br/>

1. SITUATION:<br/>
Today if we are succesful we can strike wedge to the north central part of the island halting enemy movements in the area. Our air strikes have softened up the area greatly so our ground forces have that much easier job at hand.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Modrova. UH-60 will <marker name = 'pickup'>pickup</marker> your team and ferry to the <marker name = 'lz'>LZ</marker> near first objective. From there proceed to capture <marker name = 'target1'>Opatov</marker>, then <marker name = 'meet'>meet</marker> M1A1 Platoon, then capture <marker name = 'target2'>village</marker>, <marker name = 'target3'>Dolina</marker> and <marker name = 'target4'>Mokropsy</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Your support today includes M1A1 Abrams platoon which work with you to capture the three objectives. We'll try to get some gunship support for you but cannot promise anything at the moment as the assets are busy elsewhere.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective4 = player createSimpleTask ["Capture Mokropsy"];
objective4 setSimpleTaskDescription ["Capture Mokropsy", "Capture Mokropsy", "Capture Mokropsy"];
objective3 = player createSimpleTask ["Capture Dolina"];
objective3 setSimpleTaskDescription ["Capture Dolina", "Capture Dolina", "Capture Dolina"];
objective2 = player createSimpleTask ["Capture village"];
objective2 setSimpleTaskDescription ["Capture village", "Capture village", "Capture village"];
objective1 = player createSimpleTask ["Capture Opatov"];
objective1 setSimpleTaskDescription ["Capture Opatov", "Capture Opatov", "Capture Opatov"];
