//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


I have some bullets awaiting for for the enemy, I'm expecting them to meet soon.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins, defend against enemy counter attack.



<br/><br/>PMC Bandits<br/><br/>

1. SITUATION:<br/>
Enemy is launching counter attack on several fronts, they perfectly masked this offensive into harmless activity. We wont be making that mistake again anytime soon. We will hold our grounds and defeat the enemy.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from ruins, defend against enemy counter attack.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend your position"];
objective1 setSimpleTaskDescription ["Defend your position", "Defend your position", "Defend your position"];
