//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Heh yeah today only two objectives to accomplish, boy we are getting away light. Okay jokes aside, lets focus on the mission.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Assault and capture <marker name = 'target1'>La Trinite</marker> and <marker name = 'target2'>Larche</marker> objectives.
<br/><br/>



<br/><br/>PMC Two Towns<br/><br/>

1. SITUATION:<br/>
We are approaching the northern sector of Malden where we expect to see some fierce fighting by enemys best troops.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. Assault and capture <marker name = 'target1'>La Trinite</marker> and <marker name = 'target2'>Larche</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Larche"];
objective2 setSimpleTaskDescription ["Capture Larche", "Capture Larche", "Capture Larche"];
objective1 = player createSimpleTask ["Capture La Trinite"];
objective1 setSimpleTaskDescription ["Capture La Trinite", "Capture La Trinite", "Capture La Trinite"];
