//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Well we survided that, but whats next?
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from forest. Capture <marker name = 'target1'>Petrovice</marker> and <marker name = 'target2'>Vidlakov</marker> objectives.



<br/><br/>PMC Capital<br/><br/>

1. SITUATION:<br/>
It seems that enemy has left the capitol city wide open as there is no heavy armor dug in at the time, we must use this opportunity and strike now before they can bring in some more firepower in there. By the end of the day we should have capitol of Nogova under our control.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from forest. Capture <marker name = 'target1'>Petrovice</marker> and <marker name = 'target2'>Vidlakov</marker> objectives. Use radio 0-0-1 to call Bravo to attack Petrovice and radio 0-0-2 to call Charlie to attack Vidlakov.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Bravo and Charlie mechanized infantry squads are waiting for command to attack. <marker name = 'bravo'>Bravo</marker> FUP is just west of Petrovice and <marker name = 'charlie'>Charlie</marker> FUP is west from Vidlakov. Radio 0-0-1 engages Bravo and 0-0-2 engages Charlie.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Vidlakov"];
objective2 setSimpleTaskDescription ["Capture Vidlakov", "Capture Vidlakov", "Capture Vidlakov"];
objective1 = player createSimpleTask ["Capture Petrovice"];
objective1 setSimpleTaskDescription ["Capture Petrovice", "Capture Petrovice", "Capture Petrovice"];
