//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "My way into the enemy territory. Scary huh."]];
player createDiaryRecord ["Diary", ["Mission", "You <marker name = 'start'>start</marker> in CRRC. Recon <marker name = 'target1'>isle 1</marker> and <marker name = 'target2'>isle 2</marker>.<br/><br/>PMC First Sight<br/><br/>1. WAR SITUATION:<br/>Enemy is completely in control of the Sahrani island and the small isles surrounding it. Our operations start by quietly conducting reconnaissance on the Rahmadi isle group. When our reconnaissance is complete its our plan to assault and capture this small islet to gain control of its airstrip.<br/><br/>2. YOUR MISSION:<br/>Conduct recon for two small isles.<br/><br/>3. EXECUTION/INTEL:<br/>You <marker name = 'start'>start</marker> in CRRC. Recon <marker name = 'target1'>isle 1</marker> and <marker name = 'target2'>isle 2</marker>. If you encounter hostile forces, you are cleared to shoot, clear these two isles for any OPFOR. Choose your weapons carefully, your weapons are to last for at least three missions (altough you are not supposed to engage enemy until we are ready to capture Rahmadi). Be prepared to demolition works either by AT weapons or satchel charges.<br/><br/>4. SUPPORT and ORBAT:<br/>No support expected.<br/><br/>5. SIGNALS and TACTICS:<br/>You are Special Forces squad leader. Your callsign is 1-1-A."]];

// tasks need to be in reversed order
objective2 = player createSimpleTask ["Recon isle 2"];
objective2 setSimpleTaskDescription ["Recon isle 2", "Recon isle 2", "Recon isle 2"];
objective1 = player createSimpleTask ["Recon isle 1"];
objective1 setSimpleTaskDescription ["Recon isle 1", "Recon isle 1", "Recon isle 1"];
