//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Heh I love capturing those Russians.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base, fast rope 
to <marker name = 'insert'>road</marker> and interdict Russian Major travelling
in convoy. Helo pickup at same location, return to base.



<br/><br/>PMC Ranger Path<br/><br/>

GEN SITREP<br/>
We got just hit by SCUD missiles in during the night. These missiles were launched from
somewhere in eastern Nogova but we dont have much more precise location than that. The next
thing we do is to hunt down the SCUD locations and destroy them. We are not able to deploy
Patriot units into this region by that time it would be useful.
<br/><br/>

INTEL<br/>
We have pieces of information about Russian Major travelling into north from Velka Ves 
in the next 30 minutes if not sooner. Hes most likely travelling with Spez Natz security 
team. 
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from base, helicopter will ferry you into
the large river where you fast rope down to 
the dirt <marker name = 'insert'>road</marker> between the river and mountains. Set up an ambush
there and interdict the hopefully incoming convoy where Russian Major is travelling. When you
have snatched him, the helo will pick your team up at the same location and returns you back
to base. This man is vital for Russian operations in Nogova. Do not kill the Major as we want 
to find the SCUD locations from him.
<br/><br/>

TACTICAL<br/>
Snatching the Russians. Dont let your team mates kill the Major, these guys are known with their
itchy trigger fingers.
<br/><br/>













"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Return to base"];
objective3 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective2 = player createSimpleTask ["Capture Russian Major"];
objective2 setSimpleTaskDescription ["Capture Russian Major", "Capture Russian Major", "Capture Russian Major"];
objective1 = player createSimpleTask ["Interdict convoy"];
objective1 setSimpleTaskDescription ["Interdict convoy", "Interdict convoy", "Interdict convoy"];
