//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


I hear gunfire, explosions, screams and suffering. Hooayh! Am I bad person to enjoy War so much? Hah.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from field. Capture <marker name = 'target1'>Figari</marker> and <marker name = 'target2'>Morton</marker> objectives.



<br/><br/>PMC Exchange<br/><br/>

1. SITUATION:<br/>
We are definitely looking into some heavier enemy defenses in the next couple of days. We try to focus our CAS to eliminate the enemy vehicle force as much as possible so our infantry has easier task ahead of them.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from field. Capture <marker name = 'target1'>Figari</marker> and <marker name = 'target2'>Morton</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Morton"];
objective2 setSimpleTaskDescription ["Capture Morton", "Capture Morton", "Capture Morton"];
objective1 = player createSimpleTask ["Capture Figari"];
objective1 setSimpleTaskDescription ["Capture Figari", "Capture Figari", "Capture Figari"];
