//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Assault on Everon commences and we are the tip of the spear, Hooyah!






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from the beach. Assault and capture
the Everon <marker name = 'target1'>Airbase</marker> from Russians. Secure it until reinforcements
arrive.



<br/><br/>PMC Ranger Butcher<br/><br/>

GEN SITREP<br/>
Our war with the Russians will now move into the island of Everon. They have set up quite
heavy defenses in this island and it will be fierce fight to kick them out of here. This
operation begins with capturing the airbase so we can use C-130's to bring in heavier
equipment and troops.
<br/><br/>

INTEL<br/>
Satellite imagery shows no heavy armor in the airbase area, they do have some BMP's in the 
south part near the base. Infantry is scattered around the airbase.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from the beach equipped with silenced weapons. 
Assault and capture the <marker name = 'target1'>Airbase</marker> as fast and silent as possible.
When you have neutralized the Russian troops in the airfield area, we will send you the 
reinforcement troops to take control of the airbase.. Secure the objective until the 
reinforcements have arrived. Good luck.
<br/><br/>

TACTICAL<br/>
Okay silenced weapons, play some ninja stuff out there. Be aggressive and take them out quickly
so they hopefully cant get one shot out.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Secure until backup arrives"];
objective2 setSimpleTaskDescription ["Secure until backup arrives", "Secure until backup arrives", "Secure until backup arrives"];
objective1 = player createSimpleTask ["Capture airbase"];
objective1 setSimpleTaskDescription ["Capture airbase", "Capture airbase", "Capture airbase"];
