//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Petrovice fight was intense, really intense. Everyone is like shook up after that fight.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Vidlakov. Capture <marker name = 'target1'>Neveklov</marker> and <marker name = 'target2'>Davle</marker> objectives.



<br/><br/>PMC Bridging<br/><br/>

1. SITUATION:<br/>
Enemy has ceased their attacks and are withdrading their closest forces. We must now push towards east into the next targets in our list, we must keep the enemy at run.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Vidlakov. Capture <marker name = 'target1'>Neveklov</marker> and <marker name = 'target2'>Davle</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Todays support include Bravo mechanized infantry squad and Charlie AH-64 Apache.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Davle"];
objective2 setSimpleTaskDescription ["Capture Davle", "Capture Davle", "Capture Davle"];
objective1 = player createSimpleTask ["Capture Neveklov"];
objective1 setSimpleTaskDescription ["Capture Neveklov", "Capture Neveklov", "Capture Neveklov"];
