//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Oh man that was some hellowa fight, we really stopped them on their tracks!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins. Capture <marker name = 'target1'>Fuel station</marker> and enemy <marker name = 'target2'>base</marker> objectives.



<br/><br/>PMC Goliath<br/><br/>

1. SITUATION:<br/>
Russian offensives on western sector of Kolgujev has stopped this morning, they are consolidating their forces at the moment.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from ruins. Capture <marker name = 'target1'>Fuel station</marker> and enemy <marker name = 'target2'>base</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Base"];
objective2 setSimpleTaskDescription ["Capture Base", "Capture Base", "Capture Base"];
objective1 = player createSimpleTask ["Capture Fuel station"];
objective1 setSimpleTaskDescription ["Capture Fuel station", "Capture Fuel station", "Capture Fuel station"];
