//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


So we have another large mission ahead of us, well thats why I joined the military...
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from intersection.
capture <marker name = 'target1'>hilltop</marker> objective.
capture <marker name = 'target2'>intersection</marker> objective.
capture <marker name = 'target2'>village</marker> objective.



<br/><br/>PMC Flattop<br/><br/>

1. SITUATION:<br/>
During night the enemy did try to launch an small scale attack but our forces maintained their grounds. We push foward again today.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from intersection.
capture <marker name = 'target1'>hilltop</marker> objective.
capture <marker name = 'target2'>intersection</marker> objective.
capture <marker name = 'target2'>village</marker> objective.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture village"];
objective3 setSimpleTaskDescription ["Capture village", "Capture village", "Capture village"];
objective2 = player createSimpleTask ["Capture intersection"];
objective2 setSimpleTaskDescription ["Capture intersection", "Capture intersection", "Capture intersection"];
objective1 = player createSimpleTask ["Capture hilltop"];
objective1 setSimpleTaskDescription ["Capture hilltop", "Capture hilltop", "Capture hilltop"];
