//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




This is a rescue mission, so its not just us, its the guys we are tasked to rescue.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base, 
helo <marker name = 'insert'>insert LZ</marker> is north of the area 
where <marker name = 'downed'>Apache down</marker> is located. Find the crew and get back 
to <marker name = 'extract'>Extract LZ</marker> location.
<br/><br/>
Bring them home, good luck.



<br/><br/>PMC Ranger Pilots<br/><br/>

GEN SITREP<br/>
Weather has cleared up but new stormy clouds appeared over the US base. We have apparently lost
one of our attack helicopter gunships behind enemy lines this afternoon. We will not leave 
no man behind, we are currently launching a rescue operation to get our people home.
<br/><br/>

INTEL<br/>
Mayday was heard from Charlie Black some time ago in southern Malden, they did not indicate
what was the problem but they were going down. No more radio comms have heard since but we 
do believe that they are still alive our there. The approx position of the crash site is 
between La Riviere and Chapoi, unfortunately we do not have more specific location.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from US airbase, UH-60 Black Hawk 
helo <marker name = 'insert'>insert LZ</marker> is north of the suspected crash site area 
where <marker name = 'downed'>Apache down</marker> is located. Find the crew, destroy the Apache wreck 
so it wont fall into enemy hands and get back 
to <marker name = 'extract'>Extract LZ</marker> location, use radio (0-0-1) to call extraction.
Mission is accomplished when you have destroyed the Apache, rescued the crew and returned to 
base safely.
<br/><br/>

TACTICAL<br/>
Damn this is bad one, Apache went down and we WILL get the pilots safely home. Find them, place
satchel charges under the downed bird and blow it up. Get back to the extract site as soon as 
possible, keep the site secure until extract hawk arrives. Dont make too much noise out there,
just find the crew and get back ASAP. Dont try to kill whole Russian army while youre out there.
 Goodspeed...
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Return to base"];
objective2 setSimpleTaskDescription ["Return to base", "Return to base", "Return to base"];
objective1 = player createSimpleTask ["Find crew and Destroy Apache"];
objective1 setSimpleTaskDescription ["Find crew and Destroy Apache", "Find crew and Destroy Apache", "Find crew and Destroy Apache"];
