//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Enemy is assaulting, well let them come, saves me from the trouble of going looking after them. Just give me some ammo and guys, I'll handle it.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Lany. Defend it against Russian <marker name = 'target1'>attack</marker> from N and S.



<br/><br/>PMC Spotter<br/><br/>

1. SITUATION:<br/>
Our forces in south east Nogova are pinned down by enemy attacks from both sides. We must provide them with all the support we can manage, we cant let enemy overrun them as they have made some good gains of territory in the past few days. By tomorrow we should have pretty good set of forces in the Lany region.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Lany. Defend it against Russian <marker name = 'target1'>attack</marker> from N and S.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Your <marker name = 'ussupp'>support</marker> forces are flowing in through the Nogova bridge from west. Support includes infantry, Bradleys, M1A1 Abrams and helicopter gunships.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Lany"];
objective1 setSimpleTaskDescription ["Defend Lany", "Defend Lany", "Defend Lany"];
