//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


Boy I didnt see that counterattack coming, well now I know, now I'm ready. Bring it on you bastards!
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from Montignac. Defend it against <marker name = 'target1'>attack</marker> by Russians.



<br/><br/>PMC Nightlight<br/><br/>

1. SITUATION:<br/>
As we captured Montignac in central Everon, enemy launched serious counter attack which they apparently had mobilized prior to our assault. This same wave of attacks continue now. We must keep the enemy at distance, we cannot let Montignac fall into their hands.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from Montignac. Defend it against <marker name = 'target1'>attack</marker> by Russians.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
Support forces include M1A1 Abrams platoon callsign Bravo Black. Mechanized infantry platoon callsign Charlie Black. Delta Black is medical team.
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Montignac"];
objective1 setSimpleTaskDescription ["Defend Montignac", "Defend Montignac", "Defend Montignac"];
