//auto-generated by ArmaBriefingConversion
player createDiaryRecord ["Diary", ["Diary", "Man what a mess in Chantico... quess HQ didn't see that coming. Hey after all its the grunts who's ass is on the line, right. We'll we won the battle so who cares, next time we're more careful."]];
player createDiaryRecord ["Diary", ["Mission", "1-1-A team <marker name = 'start'>start</marker> from Cedras. Capture <marker name = 'target1'>Chantico</marker> and <marker name = 'target2'>Balmopan</marker> objectives.<br/><br/>PMC Enchant<br/><br/>1. SITUATION:<br/>Enemy forces did strike us quite hard yesterday on the Chantico area, it was quite surprise to the point of intel failing so good. Seems like they have now regrouping their forces. We move forward to keep the momentum, we cannot let the enemy get upper hand at any point.<br/><br/>2. MISSION:<br/>Capture town of Chantico and Balmopan objective.<br/><br/>3. EXECUTION:<br/>1-1-A team <marker name = 'start'>start</marker> from Cedras. Capture <marker name = 'target1'>Chantico</marker> and <marker name = 'target2'>Balmopan</marker> objectives.<br/><br/>4. SERVICE AND SUPPORT<br/>AH-1 Cobra gunships and additional infantry squad is at your support today.<br/><br/>5. COMMAND AND SIGNAL<br/>"]];

// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Balmopan"];
objective2 setSimpleTaskDescription ["Capture Balmopan", "Capture Balmopan", "Capture Balmopan"];
objective1 = player createSimpleTask ["Capture Chantico"];
objective1 setSimpleTaskDescription ["Capture Chantico", "Capture Chantico", "Capture Chantico"];
