//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


I get funny feeling about this one, maybe the enemy has something special awaiting for us today, so I guess its better to keep my act tight.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base. Capture <marker name = 'target1'>farmhouse</marker> and <marker name = 'target2'>fuel station</marker> objectives.



<br/><br/>PMC Farmland<br/><br/>

1. SITUATION:<br/>
Enemy doesn't seem to want to engage our forces anywhere in the region now and we will surely take advantage of this passive mood. Hopefully by end of tomorrow we have gained much more grounds and are in better positions to continue.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from base. <marker name = 'pickup'>Embark</marker> the UH60 helo, get inserted to <marker name = 'lz1'>LZ</marker>, proceed to capture <marker name = 'target1'>farmhouse</marker> and <marker name = 'target2'>fuel station</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Fuel station"];
objective2 setSimpleTaskDescription ["Capture Fuel station", "Capture Fuel station", "Capture Fuel station"];
objective1 = player createSimpleTask ["Capture Farmhouse"];
objective1 setSimpleTaskDescription ["Capture Farmhouse", "Capture Farmhouse", "Capture Farmhouse"];
