//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Gosh, another day and another mission.
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

Special Forces <marker name = 'start'>start</marker> at Rahmadi. Assault to the <marker name = 'target1'>beach head</marker> and clear it from any enemy forces (in preparations for invasion).



"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Clear beach head"];
objective1 setSimpleTaskDescription ["Clear beach head", "Clear beach head", "Clear beach head"];
