//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "


The end is here. This is it. The final push to eject the Russian army from Kolgujev.
<br/>



"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ruins. Capture <marker name = 'target1'>base</marker>, <marker name = 'target2'>ruins</marker> and <marker name = 'target3'>harbor</marker> objectives.



<br/><br/>PMC Tip<br/><br/>

1. SITUATION:<br/>
Today we push the russians into the ocean.
<br/><br/>

2. MISSION:<br/>
<br/><br/>

3. EXECUTION:<br/>
Alpha team <marker name = 'start'>start</marker> from ruins. Capture <marker name = 'target1'>base</marker>, <marker name = 'target2'>ruins</marker> and <marker name = 'target3'>harbor</marker> objectives.
<br/><br/>

4. SERVICE AND SUPPORT<br/>
<br/><br/>

5. COMMAND AND SIGNAL<br/>
<br/><br/>




"]];
// tasks need to be in reversed order
objective3 = player createSimpleTask ["Capture Harbor"];
objective3 setSimpleTaskDescription ["Capture Harbor", "Capture Harbor", "Capture Harbor"];
objective2 = player createSimpleTask ["Capture Ruins"];
objective2 setSimpleTaskDescription ["Capture Ruins", "Capture Ruins", "Capture Ruins"];
objective1 = player createSimpleTask ["Capture Base"];
objective1 setSimpleTaskDescription ["Capture Base", "Capture Base", "Capture Base"];
