//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



So we have another large mission ahead of us, well that's why I joined the military...
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. <marker name = 'defend'>Defend</marker> Corazol south side against enemy <marker name = 'target1'>counter attack</marker> from the east and north west. Do not proceed into enemy territory under any circumstances.



"]];
// tasks need to be in reversed order
objective1 = player createSimpleTask ["Defend Corazol south side"];
objective1 setSimpleTaskDescription ["Defend Corazol south side", "Defend Corazol south side", "Defend Corazol south side"];
