//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "



Well we survived that, but whats next?
<br/>




"]];
player createDiaryRecord ["Diary", ["Mission", "

<marker name = 'start'>HQ</marker> is at Rahmadi. Re-capture <marker name = 'target1'>Carmen</marker> objective and capture <marker name = 'target2'>Tandag</marker> objective.



"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Capture Tandag"];
objective2 setSimpleTaskDescription ["Capture Tandag", "Capture Tandag", "Capture Tandag"];
objective1 = player createSimpleTask ["Re-capture Carmen"];
objective1 setSimpleTaskDescription ["Re-capture Carmen", "Re-capture Carmen", "Re-capture Carmen"];
