//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




Time to snatch that guy






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from base, helo 
will <marker name = 'insert'>insert LZ</marker> you to a field. Search 
the <marker name = 'target1'>Figari</marker> and/or <marker name = 'target2'>Provins</marker> for 
enemy Colonel. Capture him alive and bring him to <marker name = 'extract'>Extract LZ</marker> for
transport to US base.



<br/><br/>PMC Ranger Snatch<br/><br/>

GEN SITREP<br/>
Our war effort on Everon proceeds according to the plan, with minimum of losses so far. We
are hopeful that in few days we reach into Montignac and capture that important city.
<br/><br/>

INTEL<br/>
We have very good intel that Russian Colonel handeling the operations in northern sector
is meeting with his people on either Figari or Provins.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from base, UH-60 Black Hawk helicopter
will <marker name = 'insert'>insert LZ</marker> you to a field just west of your targets. 
Proceed and search 
the <marker name = 'target1'>Figari</marker> and <marker name = 'target2'>Provins</marker> for enemy 
Colonel located there. Capture him alive, do not harm him fatally, and bring him 
to the pre selected <marker name = 'extract'>Extract LZ</marker> for transportation to US base
onboard the Black Hawk helicopter. Be careful, good luck.
<br/><br/>

TACTICAL<br/>
All right, this is tricky. The Colonel should be on the houses we assume, approach carefully
dont let your team mates take him out, try to wound him if he does not surrender immediately.
Do not kill him or all of this is worth nothing.
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Extract LZ him out of there"];
objective2 setSimpleTaskDescription ["Extract LZ him out of there", "Extract LZ him out of there", "Extract LZ him out of there"];
objective1 = player createSimpleTask ["Locate and Snatch Colonel"];
objective1 setSimpleTaskDescription ["Locate and Snatch Colonel", "Locate and Snatch Colonel", "Locate and Snatch Colonel"];
