//auto-generated by ArmaBriefingConversion

player createDiaryRecord ["Diary", ["Diary", "




That airbase is going to be mother to take on, lets hope the Bravo squad does good
job in the south.






"]];
player createDiaryRecord ["Diary", ["Mission", "


Alpha team <marker name = 'start'>start</marker> from ammo depot, assault and capture
the <marker name = 'target1'>Airbase</marker> and then prepare for counter attack.
<br/><br/>
Good luck.



<br/><br/>PMC Ranger Serpent<br/><br/>

GEN SITREP<br/>
Nogova airbase is being held by Russians, for now. Our objective today is to capture
that airbase and keep it secure so we can send in airlift cargo, troops, vehicles and
that way starting the fighting in this island. By tomorrow we hopefully have setup working
base here in the west coast.
<br/><br/>

INTEL<br/>
Infantry mostly, enemy has no armor in the airbase area. They do not expect the attack
as they dont have heavy troop concentrations in the area.
<br/><br/>

ORDERS<br/>
Alpha team <marker name = 'start'>start</marker> from ammo 
depot, <marker name = 'bravo'>Bravo</marker> squad gets inserted in the south. You'll both assault 
the <marker name = 'target1'>Airbase</marker> and take it from the Russians. Make use of 
the <marker name = 'ammobox1'>Ammobox</marker> dropped for you. When you have captured the 
objective, we will send more troops by helicopter insertion to back you up. Its most certain 
that Russians launch counter attack which you must defeat. Your mission is accomplished when
you have taken the airbase and repelled possible counter attacks. Good luck.
<br/><br/>

TACTICAL<br/>
n/a
<br/><br/>













"]];
// tasks need to be in reversed order
objective2 = player createSimpleTask ["Defeat counter attacks."];
objective2 setSimpleTaskDescription ["Defeat counter attacks.", "Defeat counter attacks.", "Defeat counter attacks."];
objective1 = player createSimpleTask ["Capture airbase"];
objective1 setSimpleTaskDescription ["Capture airbase", "Capture airbase", "Capture airbase"];
